### 라이브러리 임포트 및 데이터 불러오기

In [7]:
! pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.19.1-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.52)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.5)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 7.8 MB/s eta 0:00:00
Downloading alembic-1.19.1-py3-none-any.whl (265 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 kB 9.1 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.19.1 colorlog-6.12.0 optuna-4.9.0

In [8]:
### 필요한 패키지
import torch
import pickle
import pandas as pd
import numpy as np
import shap
import matplotlib.pyplot as plt
import platform
import seaborn as sns
import optuna
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner
from lightgbm import LGBMClassifier, early_stopping, log_evaluation
from sklearn.metrics import average_precision_score, f1_score, precision_score, recall_score, roc_auc_score, precision_recall_curve, confusion_matrix

In [9]:
# pkl 파일 열기
with open('/content/drive/MyDrive/Colab Notebooks/리스크 공모전/Health_Insurance_final.pkl', 'rb') as f:
    data = pickle.load(f)
print(data.head(5))

   lapse  exposure_time  premium  seniority_insured  seniority_policy  \
0      1       0.969749  2923.32                 24                24
1      2       1.000000  1930.11                 24                24
2      2       1.000000  2020.00                 24                24
3      2       1.000000  1843.25                 24                24
4      2       1.000000  1316.03                 24                24

  type_policy_dg type_product new_business  cost_claims_year  \
0              I            S           No           8242.62
1              I            S           No            344.41
2              I            P           No            523.18
3              I            S           No            257.55
4              I            S           No            420.16

   n_medical_services  ... IICIMUN_capped help_requested  high_loss  \
0                  32  ...      22.842273              1   2.819609
1                  22  ...      22.842273              1   0.178441
2                  24  ...      17.132586              1   0.259000
3                  29  ...      -1.000000              1   0.139726
4                   9  ...      17.132586              1   0.319263

  relative_poverty  kr_age_risk  kr_premium_shock kr_shock_amount  \
0         0.858586          초고령              1.15       3361.8180
1         0.858586          초고령              1.15       2219.6265
2         0.940000          초고령              1.15       2323.0000
3        -1.000000          초고령              1.15       2119.7375
4         0.818182           장년              1.05       1381.8315

  kr_economic_stress  kr_early_laps  kr_medical_desert
0          33.957758              0       3.659259e-05
1          22.420470              0       3.659259e-05
2          23.230000              0       3.891220e-07
3          -1.000000              0      -1.000000e+00
4          13.957894              0       3.891220e-07

[5 rows x 43 columns]

In [10]:
data.columns.tolist()

['lapse',
 'exposure_time',
 'premium',
 'seniority_insured',
 'seniority_policy',
 'type_policy_dg',
 'type_product',
 'new_business',
 'cost_claims_year',
 'n_medical_services',
 'reimbursement',
 'distribution_channel',
 'age',
 'gender',
 'IICIMUN',
 'IICIPROV',
 'C_C',
 'C_H',
 'C_GI',
 'C_II',
 'C_IE_P',
 'C_IE_T',
 'C_GE_P',
 'C_GE_T',
 'ID',
 'period',
 'missing_geo_cxt',
 'is_churn',
 'cost_claims_year_capped',
 'n_medical_services_capped',
 'log_n_medical_services',
 'log_cost_claims_year',
 'C_H_num',
 'IICIMUN_capped',
 'help_requested',
 'high_loss',
 'relative_poverty',
 'kr_age_risk',
 'kr_premium_shock',
 'kr_shock_amount',
 'kr_economic_stress',
 'kr_early_laps',
 'kr_medical_desert']

In [11]:
# 결측 확인
data.isna().sum()

lapse                        0
exposure_time                0
premium                      0
seniority_insured            0
seniority_policy             0
type_policy_dg               0
type_product                 0
new_business                 0
cost_claims_year             0
n_medical_services           0
reimbursement                0
distribution_channel         0
age                          0
gender                       0
IICIMUN                      0
IICIPROV                     0
C_C                          0
C_H                          0
C_GI                         0
C_II                         0
C_IE_P                       0
C_IE_T                       0
C_GE_P                       0
C_GE_T                       0
ID                           0
period                       0
missing_geo_cxt              0
is_churn                     0
cost_claims_year_capped      0
n_medical_services_capped    0
log_n_medical_services       0
log_cost_claims_year         0
C_H_num                      0
IICIMUN_capped               0
help_requested               0
high_loss                    0
relative_poverty             0
kr_age_risk                  0
kr_premium_shock             0
kr_shock_amount              0
kr_economic_stress           0
kr_early_laps                0
kr_medical_desert            0
dtype: int64

In [12]:
# target 분포
data.is_churn.value_counts(normalize=True)

is_churn
0    0.819492
1    0.180508
Name: proportion, dtype: float64

- 데이터 분할

In [13]:
target = 'is_churn'

x_cols = [
    # 기본
    'premium', 'seniority_policy', 'type_policy_dg', 'type_product', 'new_business',
    'log_cost_claims_year', 'distribution_channel',
    # 나이 관련
    'age',
    # 성별 관련
    'gender',
    # 지역 관련
    'IICIMUN_capped', 'IICIPROV', 'C_C', 'C_H_num', 'C_GI', 'C_IE_T',
]

der_cols = [
    'missing_geo_cxt',       # 지역 결측 신호
    'high_loss',                  # 보험사 손해율
    'relative_poverty',        # 지역 내 상대적 빈곤
    'kr_premium_shock',   # 가격 인상 압박(비율 단위)
    'kr_economic_stress',  # 소득 대비 체감 부담
    # 'kr_retention_years',    # 장기 유지 혜택
    'kr_early_laps',             #신계약 위험 구간
    # 'kr_direct_channel',     # 가입 채널 영향
    'kr_medical_desert'     # 인프라 취약성
]

print(f"사용 변수 개수(기본) : {len(x_cols)}")
print(f"사용 변수 개수(파생) : {len(der_cols)}")
x_cols += der_cols
print(f"최종 변수 개수 : {len(x_cols)}개")

device = "cuda" if torch.cuda.is_available() else "cpu"

사용 변수 개수(기본) : 15
사용 변수 개수(파생) : 7
최종 변수 개수 : 22개

In [14]:
# Encoding
cat_cols = ['type_policy_dg', 'type_product', 'new_business', 'distribution_channel', 'gender', 'C_C', 'kr_early_laps']
for col in cat_cols:
    data[col] = data[col].astype('category')

In [15]:
# train/test split
train = data[data.period == 2017]
val = data[data.period == 2018]
test = data[data.period == 2019]

X_train, y_train = train[x_cols], train[target]
X_val, y_val = val[x_cols], val[target]
X_test, y_test = test[x_cols], test[target]

### threshold 튜닝 전

#### pr-auc 기준 하이퍼파라미터 튜닝

In [ ]:
# 1차 (500번 수행) : 범위가 너무 넓어 탐색 시간이 오래 걸리고, 성능 향상이 나타나지 않아 중간에 멈추고 범위 축소
def objective(trial):

    max_depth = trial.suggest_int('max_depth', 3, 15)
    max_leaves = min(2**max_depth, 1024)

    params = {
        'n_estimators': 2000,  # Early stopping을 믿고 넉넉하게 설정
        'learning_rate': trial.suggest_float('learning_rate', 0.001, 0.2, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 2, max_leaves),
        'max_depth': max_depth,
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 200),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1.0, 10.0), # 불균형 제어
        'random_state': 42,
        'n_jobs': -1,
        'verbose': -1
    }

    model = LGBMClassifier(**params)

    # Early stopping 적용 (성능 향상이 없으면 50라운드 후 학습 조기 종료)
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        eval_metric='pr_auc', # PR-AUC 평가 지표
        callbacks=[
            early_stopping(stopping_rounds=50, verbose=False),
            log_evaluation(0) # 로그 출력 숨김
        ]
    )

    preds_proba = model.predict_proba(X_val)[:, 1]
    prauc = average_precision_score(y_val, preds_proba)

    return prauc

study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, n_trials=1500) # 트리 모델에 맞춰 500회 탐색

print("\n" + "="*40)
print(f"최적 Val PR-AUC : {study.best_value:.4f}")
print(f"최적 파라미터 : {study.best_params}")
print("="*40)

[I 2026-05-10 09:13:20,866] A new study created in memory with name: no-name-3b0d7255-94d9-4678-bf0f-4cb300fef95c
[I 2026-05-10 09:13:21,278] Trial 0 finished with value: 0.34443897615275176 and parameters: {'max_depth': 7, 'learning_rate': 0.1540359659501924, 'num_leaves': 94, 'min_child_samples': 122, 'subsample': 0.4936111842654619, 'colsample_bytree': 0.49359671220172163, 'scale_pos_weight': 1.5227525095137953}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:23,113] Trial 1 finished with value: 0.31563088964612646 and parameters: {'max_depth': 14, 'learning_rate': 0.02416482602989751, 'num_leaves': 726, 'min_child_samples': 9, 'subsample': 0.9819459112971965, 'colsample_bytree': 0.899465584480253, 'scale_pos_weight': 2.9110519961044856}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:23,492] Trial 2 finished with value: 0.312782261085373 and parameters: {'max_depth': 5, 'learning_rate': 0.002642526057549917, 'num_leaves': 11, 'min_child_samples': 107, 'subsample': 0.6591670111852694, 'colsample_bytree': 0.5747374841188252, 'scale_pos_weight': 6.506676052501415}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:26,247] Trial 3 finished with value: 0.3137858094976918 and parameters: {'max_depth': 4, 'learning_rate': 0.0047014692435609715, 'num_leaves': 7, 'min_child_samples': 94, 'subsample': 0.8711055768358081, 'colsample_bytree': 0.5198042692950159, 'scale_pos_weight': 5.628109945722504}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:28,387] Trial 4 finished with value: 0.3154581641869858 and parameters: {'max_depth': 10, 'learning_rate': 0.0012790390175145834, 'num_leaves': 623, 'min_child_samples': 38, 'subsample': 0.43903095579116774, 'colsample_bytree': 0.9693313223519999, 'scale_pos_weight': 9.690688297671034}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:29,035] Trial 5 finished with value: 0.3205773005062711 and parameters: {'max_depth': 13, 'learning_rate': 0.0050225633119947675, 'num_leaves': 101, 'min_child_samples': 139, 'subsample': 0.6640914962437607, 'colsample_bytree': 0.47322294090686734, 'scale_pos_weight': 5.456592191001432}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:29,245] Trial 6 finished with value: 0.26699239242900474 and parameters: {'max_depth': 3, 'learning_rate': 0.12370108840299013, 'num_leaves': 3, 'min_child_samples': 134, 'subsample': 0.5870266456536466, 'colsample_bytree': 0.7120408127066865, 'scale_pos_weight': 5.920392514089517}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:29,528] Trial 7 finished with value: 0.28996113674745805 and parameters: {'max_depth': 5, 'learning_rate': 0.17023282716867383, 'num_leaves': 26, 'min_child_samples': 189, 'subsample': 0.9368964102565893, 'colsample_bytree': 0.7587399872866512, 'scale_pos_weight': 9.296868115208051}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:29,745] Trial 8 finished with value: 0.25805203921195535 and parameters: {'max_depth': 4, 'learning_rate': 0.0028246357083904893, 'num_leaves': 2, 'min_child_samples': 68, 'subsample': 0.6332063738136893, 'colsample_bytree': 0.5628094190643376, 'scale_pos_weight': 8.458637582367365}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:30,160] Trial 9 finished with value: 0.32425463560674234 and parameters: {'max_depth': 7, 'learning_rate': 0.004430357105538922, 'num_leaves': 70, 'min_child_samples': 32, 'subsample': 0.8813181884524238, 'colsample_bytree': 0.44473038620786254, 'scale_pos_weight': 9.881982429404655}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:30,936] Trial 10 finished with value: 0.33208114941763056 and parameters: {'max_depth': 9, 'learning_rate': 0.04215360426626737, 'num_leaves': 221, 'min_child_samples': 187, 'subsample': 0.4092206423968626, 'colsample_bytree': 0.638826005332106, 'scale_pos_weight': 1.1362981339248122}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:31,581] Trial 11 finished with value: 0.33275611896569623 and parameters: {'max_depth': 9, 'learning_rate': 0.046900796161707996, 'num_leaves': 195, 'min_child_samples': 199, 'subsample': 0.40553660142667064, 'colsample_bytree': 0.6489946910281852, 'scale_pos_weight': 1.2570725551866109}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:32,321] Trial 12 finished with value: 0.3327514739403973 and parameters: {'max_depth': 10, 'learning_rate': 0.06438454435814604, 'num_leaves': 372, 'min_child_samples': 156, 'subsample': 0.5212969114999868, 'colsample_bytree': 0.7875138644219446, 'scale_pos_weight': 1.5710773765523345}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:32,768] Trial 13 finished with value: 0.31970002945528053 and parameters: {'max_depth': 8, 'learning_rate': 0.07586711658240601, 'num_leaves': 168, 'min_child_samples': 198, 'subsample': 0.4978572252065584, 'colsample_bytree': 0.4110268703257979, 'scale_pos_weight': 3.0442511048579064}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:33,803] Trial 14 finished with value: 0.33323774075912643 and parameters: {'max_depth': 12, 'learning_rate': 0.01530954802785237, 'num_leaves': 1024, 'min_child_samples': 161, 'subsample': 0.7715007264424556, 'colsample_bytree': 0.639237841557856, 'scale_pos_weight': 3.0105150161221053}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:35,160] Trial 15 finished with value: 0.3333702086117312 and parameters: {'max_depth': 12, 'learning_rate': 0.012053500441216513, 'num_leaves': 989, 'min_child_samples': 159, 'subsample': 0.7710260047420174, 'colsample_bytree': 0.6203451344986165, 'scale_pos_weight': 3.411521385014131}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:36,410] Trial 16 finished with value: 0.32889150621495056 and parameters: {'max_depth': 15, 'learning_rate': 0.009836609152475482, 'num_leaves': 918, 'min_child_samples': 113, 'subsample': 0.7537591011074556, 'colsample_bytree': 0.5201118675949149, 'scale_pos_weight': 4.36579935167426}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:40,440] Trial 17 finished with value: 0.32795665733259577 and parameters: {'max_depth': 12, 'learning_rate': 0.0200374117785245, 'num_leaves': 365, 'min_child_samples': 161, 'subsample': 0.7597011029541516, 'colsample_bytree': 0.8235632814182953, 'scale_pos_weight': 3.8870163619314235}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:41,023] Trial 18 finished with value: 0.32007204242404946 and parameters: {'max_depth': 7, 'learning_rate': 0.010046769224667736, 'num_leaves': 43, 'min_child_samples': 83, 'subsample': 0.8331672883364218, 'colsample_bytree': 0.5783718515453435, 'scale_pos_weight': 2.476901600153666}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:41,811] Trial 19 finished with value: 0.3228937996109455 and parameters: {'max_depth': 11, 'learning_rate': 0.027587062472754494, 'num_leaves': 799, 'min_child_samples': 128, 'subsample': 0.578217769583813, 'colsample_bytree': 0.5023855875016573, 'scale_pos_weight': 4.605027111995665}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:42,494] Trial 20 finished with value: 0.3240510668884545 and parameters: {'max_depth': 7, 'learning_rate': 0.010315866444684095, 'num_leaves': 74, 'min_child_samples': 67, 'subsample': 0.7303416674801918, 'colsample_bytree': 0.4002187716621855, 'scale_pos_weight': 2.062936628658872}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:43,739] Trial 21 finished with value: 0.3330923121098166 and parameters: {'max_depth': 12, 'learning_rate': 0.014869150469480934, 'num_leaves': 1007, 'min_child_samples': 165, 'subsample': 0.8031623088818842, 'colsample_bytree': 0.6401781238949421, 'scale_pos_weight': 3.3056516262976188}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:44,685] Trial 22 finished with value: 0.31867852890249293 and parameters: {'max_depth': 13, 'learning_rate': 0.11162062495890356, 'num_leaves': 1021, 'min_child_samples': 150, 'subsample': 0.7917264180195059, 'colsample_bytree': 0.6989749547037227, 'scale_pos_weight': 2.1686259390060827}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:45,256] Trial 23 finished with value: 0.2848985932741632 and parameters: {'max_depth': 11, 'learning_rate': 0.19603990887062317, 'num_leaves': 877, 'min_child_samples': 179, 'subsample': 0.7059861756387037, 'colsample_bytree': 0.6043611056936495, 'scale_pos_weight': 3.7611999449317786}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:48,117] Trial 24 finished with value: 0.33036629242937227 and parameters: {'max_depth': 15, 'learning_rate': 0.0010243809518580694, 'num_leaves': 566, 'min_child_samples': 122, 'subsample': 0.8571384757342315, 'colsample_bytree': 0.7140253553519993, 'scale_pos_weight': 7.428516655953963}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:49,791] Trial 25 finished with value: 0.33626095228033875 and parameters: {'max_depth': 13, 'learning_rate': 0.007362701622499002, 'num_leaves': 443, 'min_child_samples': 174, 'subsample': 0.6003761913771005, 'colsample_bytree': 0.6612949940103852, 'scale_pos_weight': 2.0425277594335096}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:55,206] Trial 26 finished with value: 0.33473226794546296 and parameters: {'max_depth': 14, 'learning_rate': 0.006349386109485041, 'num_leaves': 410, 'min_child_samples': 174, 'subsample': 0.5169151862211332, 'colsample_bytree': 0.6823477444627337, 'scale_pos_weight': 1.8185372627096115}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:13:57,410] Trial 27 finished with value: 0.3287415373422342 and parameters: {'max_depth': 14, 'learning_rate': 0.006745149719381329, 'num_leaves': 412, 'min_child_samples': 178, 'subsample': 0.4924098254474013, 'colsample_bytree': 0.8543888596860164, 'scale_pos_weight': 1.7358017051379793}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:14:01,096] Trial 28 finished with value: 0.333748951449431 and parameters: {'max_depth': 14, 'learning_rate': 0.00228607954183431, 'num_leaves': 287, 'min_child_samples': 142, 'subsample': 0.5582606051501756, 'colsample_bytree': 0.7582757748947848, 'scale_pos_weight': 2.3236542797495563}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:14:03,322] Trial 29 finished with value: 0.308975545343089 and parameters: {'max_depth': 14, 'learning_rate': 0.0073821600277801545, 'num_leaves': 494, 'min_child_samples': 6, 'subsample': 0.4667798937573922, 'colsample_bytree': 0.932301926014856, 'scale_pos_weight': 2.4391239480815705}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:14:03,640] Trial 30 finished with value: 0.31668634872014756 and parameters: {'max_depth': 6, 'learning_rate': 0.0335711853357878, 'num_leaves': 19, 'min_child_samples': 174, 'subsample': 0.5352030483132804, 'colsample_bytree': 0.6744386280216468, 'scale_pos_weight': 4.644930051331874}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:14:15,966] Trial 31 finished with value: 0.3333065102186583 and parameters: {'max_depth': 15, 'learning_rate': 0.0020256393207783462, 'num_leaves': 287, 'min_child_samples': 144, 'subsample': 0.5760786826685277, 'colsample_bytree': 0.7423598239018024, 'scale_pos_weight': 1.0752247650276177}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:14:22,426] Trial 32 finished with value: 0.32837231223881236 and parameters: {'max_depth': 13, 'learning_rate': 0.002381376867835594, 'num_leaves': 470, 'min_child_samples': 122, 'subsample': 0.6304487138321956, 'colsample_bytree': 0.8507105788852283, 'scale_pos_weight': 2.539262923179509}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:14:25,539] Trial 33 finished with value: 0.33185541461422835 and parameters: {'max_depth': 14, 'learning_rate': 0.003497262304753681, 'num_leaves': 269, 'min_child_samples': 101, 'subsample': 0.5465281736938895, 'colsample_bytree': 0.7919319039325382, 'scale_pos_weight': 1.9619903667394754}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:14:37,460] Trial 34 finished with value: 0.3346421968399757 and parameters: {'max_depth': 14, 'learning_rate': 0.0017850950693453782, 'num_leaves': 670, 'min_child_samples': 144, 'subsample': 0.4556042778778444, 'colsample_bytree': 0.5451451341173948, 'scale_pos_weight': 1.6417677986519053}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:14:50,669] Trial 35 finished with value: 0.3361807304127174 and parameters: {'max_depth': 13, 'learning_rate': 0.0014720375558799565, 'num_leaves': 670, 'min_child_samples': 172, 'subsample': 0.4534263004686895, 'colsample_bytree': 0.5476809187099367, 'scale_pos_weight': 1.6134818139925289}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:02,907] Trial 36 finished with value: 0.33487920748349964 and parameters: {'max_depth': 11, 'learning_rate': 0.001549162084803919, 'num_leaves': 577, 'min_child_samples': 172, 'subsample': 0.620817971015006, 'colsample_bytree': 0.47345054929964386, 'scale_pos_weight': 1.5148705773532536}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:18,495] Trial 37 finished with value: 0.33063914720048176 and parameters: {'max_depth': 10, 'learning_rate': 0.001386324120281215, 'num_leaves': 725, 'min_child_samples': 112, 'subsample': 0.6132323285417599, 'colsample_bytree': 0.4921864556904239, 'scale_pos_weight': 1.0205633932785099}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:20,234] Trial 38 finished with value: 0.3287045488345074 and parameters: {'max_depth': 11, 'learning_rate': 0.0032537185314502237, 'num_leaves': 600, 'min_child_samples': 189, 'subsample': 0.6646221441769895, 'colsample_bytree': 0.4664102747098011, 'scale_pos_weight': 2.7750479578362652}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:21,256] Trial 39 finished with value: 0.3165766527583969 and parameters: {'max_depth': 8, 'learning_rate': 0.0017085521905574987, 'num_leaves': 132, 'min_child_samples': 84, 'subsample': 0.6805346981770676, 'colsample_bytree': 0.437905197427617, 'scale_pos_weight': 5.047350001515381}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:22,588] Trial 40 finished with value: 0.325669753267508 and parameters: {'max_depth': 9, 'learning_rate': 0.0011390994843955699, 'num_leaves': 451, 'min_child_samples': 170, 'subsample': 0.5986740169218591, 'colsample_bytree': 0.5312877064326242, 'scale_pos_weight': 6.453575733071828}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:28,630] Trial 41 finished with value: 0.33632082094437804 and parameters: {'max_depth': 13, 'learning_rate': 0.005498773521499415, 'num_leaves': 543, 'min_child_samples': 177, 'subsample': 0.497983245506346, 'colsample_bytree': 0.5569001947431667, 'scale_pos_weight': 1.4995279506967714}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:32,737] Trial 42 finished with value: 0.335249250850969 and parameters: {'max_depth': 13, 'learning_rate': 0.004249135045939332, 'num_leaves': 558, 'min_child_samples': 184, 'subsample': 0.488112630804642, 'colsample_bytree': 0.5840429837304397, 'scale_pos_weight': 1.474804075628275}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:36,741] Trial 43 finished with value: 0.335180997594763 and parameters: {'max_depth': 13, 'learning_rate': 0.0044749435667053574, 'num_leaves': 679, 'min_child_samples': 187, 'subsample': 0.4320402535711285, 'colsample_bytree': 0.5794059267039341, 'scale_pos_weight': 1.414907593100496}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:43,751] Trial 44 finished with value: 0.33458254434693663 and parameters: {'max_depth': 13, 'learning_rate': 0.005644113226016966, 'num_leaves': 533, 'min_child_samples': 199, 'subsample': 0.48097494337723173, 'colsample_bytree': 0.600814366863545, 'scale_pos_weight': 1.0137709502548926}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:44,121] Trial 45 finished with value: 0.31390514649831014 and parameters: {'max_depth': 5, 'learning_rate': 0.007497515057644974, 'num_leaves': 11, 'min_child_samples': 23, 'subsample': 0.4361686993931365, 'colsample_bytree': 0.5527375006435741, 'scale_pos_weight': 2.812736947280042}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:47,416] Trial 46 finished with value: 0.3347067988077466 and parameters: {'max_depth': 13, 'learning_rate': 0.0035278809458732514, 'num_leaves': 783, 'min_child_samples': 153, 'subsample': 0.9906606759844861, 'colsample_bytree': 0.5834969419283099, 'scale_pos_weight': 2.04061603531156}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:47,788] Trial 47 finished with value: 0.32277135743069507 and parameters: {'max_depth': 6, 'learning_rate': 0.004959118071787091, 'num_leaves': 37, 'min_child_samples': 186, 'subsample': 0.5118885480299403, 'colsample_bytree': 0.4968569995844796, 'scale_pos_weight': 7.728336544550904}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:48,853] Trial 48 finished with value: 0.3360489382541722 and parameters: {'max_depth': 3, 'learning_rate': 0.020364164166497948, 'num_leaves': 2, 'min_child_samples': 58, 'subsample': 0.4055794360297927, 'colsample_bytree': 0.5451062652716436, 'scale_pos_weight': 1.4357025466442552}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:49,129] Trial 49 finished with value: 0.3120101372515506 and parameters: {'max_depth': 5, 'learning_rate': 0.022997102766977116, 'num_leaves': 6, 'min_child_samples': 52, 'subsample': 0.4082477727854905, 'colsample_bytree': 0.5348124179009061, 'scale_pos_weight': 3.3327029724441024}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:49,334] Trial 50 finished with value: 0.24883486628338808 and parameters: {'max_depth': 3, 'learning_rate': 0.12527403607224852, 'num_leaves': 2, 'min_child_samples': 61, 'subsample': 0.4548919664154476, 'colsample_bytree': 0.4534788306862385, 'scale_pos_weight': 4.00824288318887}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:49,614] Trial 51 finished with value: 0.32392119288603927 and parameters: {'max_depth': 4, 'learning_rate': 0.06126774618272274, 'num_leaves': 5, 'min_child_samples': 84, 'subsample': 0.49011770309766184, 'colsample_bytree': 0.615151763291948, 'scale_pos_weight': 1.5553413391799282}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:54,542] Trial 52 finished with value: 0.3231091005871666 and parameters: {'max_depth': 12, 'learning_rate': 0.019688357461096553, 'num_leaves': 648, 'min_child_samples': 19, 'subsample': 0.4217694674450237, 'colsample_bytree': 0.5659546236970812, 'scale_pos_weight': 1.8128868918171535}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:56,018] Trial 53 finished with value: 0.3261156181591466 and parameters: {'max_depth': 3, 'learning_rate': 0.002757468392333236, 'num_leaves': 4, 'min_child_samples': 39, 'subsample': 0.4700196716340189, 'colsample_bytree': 0.5134914678742856, 'scale_pos_weight': 1.3995804148378876}. Best is trial 0 with value: 0.34443897615275176.
[I 2026-05-10 09:15:57,369] Trial 54 finished with value: 0.3285970836458968 and parameters: {'max_depth': 12, 'learning_rate': 0.009200498309859308, 'num_leaves': 543, 'min_child_samples': 133, 'subsample': 0.44896219877096005, 'colsample_bytree': 0.48446382488911927, 'scale_pos_weight': 2.589024882341371}. Best is trial 0 with value: 0.34443897615275176.

KeyboardInterrupt:

In [ ]:
# 1차 탐색 기준 최고 파라미터 조합
print("현재까지 최고 Val PR-AUC:", study.best_value)
print("최고 파라미터 조합:\n", study.best_params)

현재까지 최고 Val PR-AUC: 0.34443897615275176
최고 파라미터 조합:
 {'max_depth': 7, 'learning_rate': 0.1540359659501924, 'num_leaves': 94, 'min_child_samples': 122, 'subsample': 0.4936111842654619, 'colsample_bytree': 0.49359671220172163, 'scale_pos_weight': 1.5227525095137953}

In [ ]:
# 2차 탐색
def objective(trial):
    max_depth = trial.suggest_int('max_depth', 5, 9)   # 최적값 7 중심으로 좁은 범위 설정
    max_leaves = min(2 ** max_depth, 150) # max_depth에 맞춘 유연한 잎의 개수
    min_leaves = min(70, max_leaves)
    params = {
        'n_estimators': 2000,
        'learning_rate': trial.suggest_float('learning_rate', 0.08, 0.25), # 0.154 주변 정밀 탐색
        'max_depth': max_depth,
        'num_leaves': trial.suggest_int('num_leaves', min_leaves, max_leaves),
        'min_child_samples': trial.suggest_int('min_child_samples', 100, 160), # 122 주변 탐색
        'subsample': trial.suggest_float('subsample', 0.35, 0.65),         # 0.49 주변 탐색 (데이터와 피처를 절반 정도 사용)
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.35, 0.65),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1.0, 2.5), # 1.52 주변 탐색
        'random_state': 42,
        'n_jobs': -1,
        'verbose': -1
    }

    model = LGBMClassifier(**params)

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        eval_metric='pr_auc',
        callbacks=[
            early_stopping(stopping_rounds=50, verbose=False),
            log_evaluation(0)
        ]
    )

    preds_proba = model.predict_proba(X_val)[:, 1]
    prauc = average_precision_score(y_val, preds_proba)

    return prauc

study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, n_trials=500)

print("\n" + "="*40)
print(f"최종 정밀 탐색 최고 PR-AUC : {study.best_value:.4f}")
print(f"최적 파라미터 : {study.best_params}")
print("="*40)

[I 2026-05-10 09:33:27,428] A new study created in memory with name: no-name-aea674ff-2d1c-497d-9203-090978d3d178
[I 2026-05-10 09:33:29,281] Trial 0 finished with value: 0.3206114862894348 and parameters: {'max_depth': 6, 'learning_rate': 0.24162143208968573, 'num_leaves': 64, 'min_child_samples': 144, 'subsample': 0.529597545259111, 'colsample_bytree': 0.3968055921327309, 'scale_pos_weight': 1.233991780504304}. Best is trial 0 with value: 0.3206114862894348.
[I 2026-05-10 09:33:29,570] Trial 1 finished with value: 0.32236341347749425 and parameters: {'max_depth': 5, 'learning_rate': 0.227249944781739, 'num_leaves': 32, 'min_child_samples': 136, 'subsample': 0.5624217733388137, 'colsample_bytree': 0.3561753482887407, 'scale_pos_weight': 2.4548647782429915}. Best is trial 1 with value: 0.32236341347749425.
[I 2026-05-10 09:33:29,998] Trial 2 finished with value: 0.3267612167974169 and parameters: {'max_depth': 9, 'learning_rate': 0.11609764881530694, 'num_leaves': 84, 'min_child_samples': 111, 'subsample': 0.4412726728878613, 'colsample_bytree': 0.5074269294896714, 'scale_pos_weight': 1.6479175279631737}. Best is trial 2 with value: 0.3267612167974169.
[I 2026-05-10 09:33:30,304] Trial 3 finished with value: 0.3457542020576446 and parameters: {'max_depth': 6, 'learning_rate': 0.1840149921028045, 'num_leaves': 64, 'min_child_samples': 108, 'subsample': 0.43764339456056545, 'colsample_bytree': 0.4599085529881075, 'scale_pos_weight': 1.6841049763255538}. Best is trial 3 with value: 0.3457542020576446.
[I 2026-05-10 09:33:30,778] Trial 4 finished with value: 0.34314540213908934 and parameters: {'max_depth': 8, 'learning_rate': 0.11394454296692116, 'num_leaves': 111, 'min_child_samples': 136, 'subsample': 0.3639351238159993, 'colsample_bytree': 0.5322634555704315, 'scale_pos_weight': 1.2557861855309373}. Best is trial 3 with value: 0.3457542020576446.
[I 2026-05-10 09:33:31,054] Trial 5 finished with value: 0.34874871025313403 and parameters: {'max_depth': 5, 'learning_rate': 0.24131054133306662, 'num_leaves': 32, 'min_child_samples': 158, 'subsample': 0.5925192044349383, 'colsample_bytree': 0.4413841307520112, 'scale_pos_weight': 1.1465081710095757}. Best is trial 5 with value: 0.34874871025313403.
[I 2026-05-10 09:33:31,465] Trial 6 finished with value: 0.3212978386298455 and parameters: {'max_depth': 8, 'learning_rate': 0.15482592393573222, 'num_leaves': 79, 'min_child_samples': 130, 'subsample': 0.3603165563345655, 'colsample_bytree': 0.6227961206236347, 'scale_pos_weight': 1.3881699724000254}. Best is trial 5 with value: 0.34874871025313403.
[I 2026-05-10 09:33:31,901] Trial 7 finished with value: 0.3115026037711183 and parameters: {'max_depth': 8, 'learning_rate': 0.13299088293519987, 'num_leaves': 112, 'min_child_samples': 133, 'subsample': 0.4054563366576581, 'colsample_bytree': 0.6408753883293676, 'scale_pos_weight': 2.162699235041672}. Best is trial 5 with value: 0.34874871025313403.
[I 2026-05-10 09:33:32,323] Trial 8 finished with value: 0.3297783170309071 and parameters: {'max_depth': 9, 'learning_rate': 0.2321206495727003, 'num_leaves': 118, 'min_child_samples': 156, 'subsample': 0.3765477506155758, 'colsample_bytree': 0.40879485872574356, 'scale_pos_weight': 1.0678409333658072}. Best is trial 5 with value: 0.34874871025313403.
[I 2026-05-10 09:33:32,682] Trial 9 finished with value: 0.34921152823784335 and parameters: {'max_depth': 6, 'learning_rate': 0.14607513924721194, 'num_leaves': 64, 'min_child_samples': 116, 'subsample': 0.5986212527455788, 'colsample_bytree': 0.45702599800807675, 'scale_pos_weight': 1.4214017645310713}. Best is trial 9 with value: 0.34921152823784335.
[I 2026-05-10 09:33:34,216] Trial 10 finished with value: 0.328365851594228 and parameters: {'max_depth': 6, 'learning_rate': 0.08101952110248893, 'num_leaves': 64, 'min_child_samples': 118, 'subsample': 0.6356323343526566, 'colsample_bytree': 0.5645508836590385, 'scale_pos_weight': 2.035370610353718}. Best is trial 9 with value: 0.34921152823784335.
[I 2026-05-10 09:33:36,283] Trial 11 finished with value: 0.34784080434500875 and parameters: {'max_depth': 5, 'learning_rate': 0.18977322268092756, 'num_leaves': 32, 'min_child_samples': 159, 'subsample': 0.6284161315461605, 'colsample_bytree': 0.45836618119030037, 'scale_pos_weight': 1.0095716316662735}. Best is trial 9 with value: 0.34921152823784335.
[I 2026-05-10 09:33:36,576] Trial 12 finished with value: 0.3433015067395386 and parameters: {'max_depth': 5, 'learning_rate': 0.20713982728857502, 'num_leaves': 32, 'min_child_samples': 121, 'subsample': 0.5800263355843891, 'colsample_bytree': 0.4434270226782223, 'scale_pos_weight': 1.4838971710342872}. Best is trial 9 with value: 0.34921152823784335.
[I 2026-05-10 09:33:36,989] Trial 13 finished with value: 0.34861074426172445 and parameters: {'max_depth': 7, 'learning_rate': 0.15659578596637075, 'num_leaves': 94, 'min_child_samples': 101, 'subsample': 0.5907134763892936, 'colsample_bytree': 0.4833470219483324, 'scale_pos_weight': 1.5214501457448741}. Best is trial 9 with value: 0.34921152823784335.
[I 2026-05-10 09:33:37,297] Trial 14 finished with value: 0.32582940620255224 and parameters: {'max_depth': 6, 'learning_rate': 0.1742211226297044, 'num_leaves': 64, 'min_child_samples': 151, 'subsample': 0.5020721632408787, 'colsample_bytree': 0.4092651679870232, 'scale_pos_weight': 1.8465550190245952}. Best is trial 9 with value: 0.34921152823784335.
[I 2026-05-10 09:33:37,677] Trial 15 finished with value: 0.32778780265908597 and parameters: {'max_depth': 7, 'learning_rate': 0.20938674807460259, 'num_leaves': 80, 'min_child_samples': 122, 'subsample': 0.6494104125170406, 'colsample_bytree': 0.5689504488595104, 'scale_pos_weight': 1.2385795619919986}. Best is trial 9 with value: 0.34921152823784335.
[I 2026-05-10 09:33:37,994] Trial 16 finished with value: 0.32659014387315455 and parameters: {'max_depth': 5, 'learning_rate': 0.1380598864707475, 'num_leaves': 32, 'min_child_samples': 144, 'subsample': 0.5450177195598633, 'colsample_bytree': 0.3688330631038024, 'scale_pos_weight': 1.3701155523025579}. Best is trial 9 with value: 0.34921152823784335.
[I 2026-05-10 09:33:38,369] Trial 17 finished with value: 0.33749067056540605 and parameters: {'max_depth': 6, 'learning_rate': 0.09141646004384966, 'num_leaves': 64, 'min_child_samples': 128, 'subsample': 0.5911464941800209, 'colsample_bytree': 0.4381150822050288, 'scale_pos_weight': 1.9077132194422797}. Best is trial 9 with value: 0.34921152823784335.
[I 2026-05-10 09:33:38,678] Trial 18 finished with value: 0.3545077316287778 and parameters: {'max_depth': 5, 'learning_rate': 0.20105749418145935, 'num_leaves': 32, 'min_child_samples': 114, 'subsample': 0.4994349427504536, 'colsample_bytree': 0.5073197643492163, 'scale_pos_weight': 1.1770309877613616}. Best is trial 18 with value: 0.3545077316287778.
[I 2026-05-10 09:33:39,088] Trial 19 finished with value: 0.32001772495908265 and parameters: {'max_depth': 7, 'learning_rate': 0.19886094419715852, 'num_leaves': 97, 'min_child_samples': 113, 'subsample': 0.48832497192298796, 'colsample_bytree': 0.5250567558014941, 'scale_pos_weight': 1.5375854271858127}. Best is trial 18 with value: 0.3545077316287778.
[I 2026-05-10 09:33:39,435] Trial 20 finished with value: 0.3395868727698109 and parameters: {'max_depth': 6, 'learning_rate': 0.1727404409616713, 'num_leaves': 64, 'min_child_samples': 101, 'subsample': 0.48856531097233313, 'colsample_bytree': 0.5569023275635302, 'scale_pos_weight': 1.3596607941130772}. Best is trial 18 with value: 0.3545077316287778.
[I 2026-05-10 09:33:39,731] Trial 21 finished with value: 0.3569392726913623 and parameters: {'max_depth': 5, 'learning_rate': 0.24993305761580628, 'num_leaves': 32, 'min_child_samples': 117, 'subsample': 0.6122695337165464, 'colsample_bytree': 0.49801236968220003, 'scale_pos_weight': 1.1160489471582762}. Best is trial 21 with value: 0.3569392726913623.
[I 2026-05-10 09:33:40,063] Trial 22 finished with value: 0.3568538123632107 and parameters: {'max_depth': 5, 'learning_rate': 0.21924145395986516, 'num_leaves': 32, 'min_child_samples': 115, 'subsample': 0.6167905508846909, 'colsample_bytree': 0.48905094036052815, 'scale_pos_weight': 1.0917320636575425}. Best is trial 21 with value: 0.3569392726913623.
[I 2026-05-10 09:33:40,366] Trial 23 finished with value: 0.3560466450468426 and parameters: {'max_depth': 5, 'learning_rate': 0.22018747833873675, 'num_leaves': 32, 'min_child_samples': 106, 'subsample': 0.5222878378858655, 'colsample_bytree': 0.48958736209063736, 'scale_pos_weight': 1.1273281895405773}. Best is trial 21 with value: 0.3569392726913623.
[I 2026-05-10 09:33:40,664] Trial 24 finished with value: 0.36038624557665044 and parameters: {'max_depth': 5, 'learning_rate': 0.22299289015529947, 'num_leaves': 32, 'min_child_samples': 106, 'subsample': 0.6167953719919546, 'colsample_bytree': 0.48474251361640164, 'scale_pos_weight': 1.0534941356089682}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:40,972] Trial 25 finished with value: 0.32911865261958173 and parameters: {'max_depth': 5, 'learning_rate': 0.24972059219728815, 'num_leaves': 32, 'min_child_samples': 124, 'subsample': 0.6182103994213654, 'colsample_bytree': 0.5898785873570312, 'scale_pos_weight': 1.0172476854540389}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:41,271] Trial 26 finished with value: 0.3495575830731116 and parameters: {'max_depth': 5, 'learning_rate': 0.21995634467625966, 'num_leaves': 32, 'min_child_samples': 108, 'subsample': 0.6122454922526357, 'colsample_bytree': 0.4789923676749066, 'scale_pos_weight': 1.2866837038758234}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:41,610] Trial 27 finished with value: 0.34050471756390854 and parameters: {'max_depth': 6, 'learning_rate': 0.23363859367012924, 'num_leaves': 64, 'min_child_samples': 105, 'subsample': 0.5690228910049765, 'colsample_bytree': 0.5352711042732616, 'scale_pos_weight': 1.1205892573824585}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:41,947] Trial 28 finished with value: 0.28629200049196374 and parameters: {'max_depth': 7, 'learning_rate': 0.21558640391936937, 'num_leaves': 73, 'min_child_samples': 126, 'subsample': 0.649240948544292, 'colsample_bytree': 0.5132498243721176, 'scale_pos_weight': 2.2621364183671924}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:42,475] Trial 29 finished with value: 0.33320827086098115 and parameters: {'max_depth': 5, 'learning_rate': 0.24964252674299392, 'num_leaves': 32, 'min_child_samples': 119, 'subsample': 0.5448936156909238, 'colsample_bytree': 0.4236412840197612, 'scale_pos_weight': 1.0030898396573704}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:42,788] Trial 30 finished with value: 0.32840945278938616 and parameters: {'max_depth': 6, 'learning_rate': 0.23779670337000142, 'num_leaves': 64, 'min_child_samples': 110, 'subsample': 0.6096418891567859, 'colsample_bytree': 0.3838345980058591, 'scale_pos_weight': 1.2834997244351705}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:43,271] Trial 31 finished with value: 0.3506984777820685 and parameters: {'max_depth': 5, 'learning_rate': 0.22114469301049086, 'num_leaves': 32, 'min_child_samples': 105, 'subsample': 0.5261808254311736, 'colsample_bytree': 0.4897001989282671, 'scale_pos_weight': 1.1937426269720506}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:43,565] Trial 32 finished with value: 0.35658234844068615 and parameters: {'max_depth': 5, 'learning_rate': 0.22223715138167227, 'num_leaves': 32, 'min_child_samples': 105, 'subsample': 0.5598337363996173, 'colsample_bytree': 0.4820747562996103, 'scale_pos_weight': 1.0987463131853394}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:44,019] Trial 33 finished with value: 0.3456735495604879 and parameters: {'max_depth': 5, 'learning_rate': 0.1908511575173761, 'num_leaves': 32, 'min_child_samples': 100, 'subsample': 0.5574146842504113, 'colsample_bytree': 0.4662551593233019, 'scale_pos_weight': 1.0872138460604024}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:44,297] Trial 34 finished with value: 0.28408175240657624 and parameters: {'max_depth': 5, 'learning_rate': 0.22724148512678938, 'num_leaves': 32, 'min_child_samples': 116, 'subsample': 0.5711791993624251, 'colsample_bytree': 0.5433928055018042, 'scale_pos_weight': 2.4608854333018897}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:44,604] Trial 35 finished with value: 0.29199791297519956 and parameters: {'max_depth': 6, 'learning_rate': 0.24414739616827724, 'num_leaves': 64, 'min_child_samples': 111, 'subsample': 0.6292617531394563, 'colsample_bytree': 0.506304605249363, 'scale_pos_weight': 1.618175839030315}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:44,893] Trial 36 finished with value: 0.34533589129443043 and parameters: {'max_depth': 5, 'learning_rate': 0.2287496814980225, 'num_leaves': 32, 'min_child_samples': 104, 'subsample': 0.6002127674014293, 'colsample_bytree': 0.47432935773619017, 'scale_pos_weight': 1.224622896497907}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:45,225] Trial 37 finished with value: 0.350516987893714 and parameters: {'max_depth': 5, 'learning_rate': 0.2099753767143803, 'num_leaves': 32, 'min_child_samples': 110, 'subsample': 0.6199680100693419, 'colsample_bytree': 0.5191557750252901, 'scale_pos_weight': 1.2954944034173503}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:45,553] Trial 38 finished with value: 0.33353978711233956 and parameters: {'max_depth': 6, 'learning_rate': 0.24074682279467724, 'num_leaves': 64, 'min_child_samples': 114, 'subsample': 0.5519476508708335, 'colsample_bytree': 0.49096170312264914, 'scale_pos_weight': 1.1352950845172518}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:45,857] Trial 39 finished with value: 0.33020742619630133 and parameters: {'max_depth': 5, 'learning_rate': 0.18204099800773563, 'num_leaves': 32, 'min_child_samples': 108, 'subsample': 0.5768438168163164, 'colsample_bytree': 0.5855029806469519, 'scale_pos_weight': 1.074839899476093}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:46,343] Trial 40 finished with value: 0.3392789573463454 and parameters: {'max_depth': 9, 'learning_rate': 0.22827464217795354, 'num_leaves': 73, 'min_child_samples': 118, 'subsample': 0.637691042741824, 'colsample_bytree': 0.4512155047285963, 'scale_pos_weight': 1.7443495561168858}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:49,369] Trial 41 finished with value: 0.3553052404247853 and parameters: {'max_depth': 5, 'learning_rate': 0.21699277613219528, 'num_leaves': 32, 'min_child_samples': 104, 'subsample': 0.5266719433539816, 'colsample_bytree': 0.4967640054876893, 'scale_pos_weight': 1.1644870508214753}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:49,701] Trial 42 finished with value: 0.3459203714810589 and parameters: {'max_depth': 5, 'learning_rate': 0.19665038496384823, 'num_leaves': 32, 'min_child_samples': 107, 'subsample': 0.5087293816366594, 'colsample_bytree': 0.4705455911495602, 'scale_pos_weight': 1.0777699343524587}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:49,998] Trial 43 finished with value: 0.35973099199791536 and parameters: {'max_depth': 5, 'learning_rate': 0.220332831572609, 'num_leaves': 32, 'min_child_samples': 112, 'subsample': 0.45987838315548113, 'colsample_bytree': 0.4991480723520929, 'scale_pos_weight': 1.002337407540614}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:50,299] Trial 44 finished with value: 0.35216445616227715 and parameters: {'max_depth': 5, 'learning_rate': 0.23619522353457256, 'num_leaves': 32, 'min_child_samples': 112, 'subsample': 0.4511825624412329, 'colsample_bytree': 0.5470470111434323, 'scale_pos_weight': 1.0416817997758188}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:50,636] Trial 45 finished with value: 0.3242895215697136 and parameters: {'max_depth': 6, 'learning_rate': 0.2054379929650102, 'num_leaves': 64, 'min_child_samples': 116, 'subsample': 0.4632192320729575, 'colsample_bytree': 0.4284613943909281, 'scale_pos_weight': 1.3244996942793912}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:50,931] Trial 46 finished with value: 0.34867309464044716 and parameters: {'max_depth': 5, 'learning_rate': 0.2140520903870133, 'num_leaves': 32, 'min_child_samples': 122, 'subsample': 0.42736433126502527, 'colsample_bytree': 0.5017942695132793, 'scale_pos_weight': 1.4304307549423154}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:51,226] Trial 47 finished with value: 0.3560187285774204 and parameters: {'max_depth': 5, 'learning_rate': 0.22448672904517145, 'num_leaves': 32, 'min_child_samples': 136, 'subsample': 0.4039100982581401, 'colsample_bytree': 0.5275155340304111, 'scale_pos_weight': 1.2099895789100321}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:51,671] Trial 48 finished with value: 0.33730992157811973 and parameters: {'max_depth': 8, 'learning_rate': 0.24263969075936864, 'num_leaves': 147, 'min_child_samples': 110, 'subsample': 0.4698919499805639, 'colsample_bytree': 0.46321309752332623, 'scale_pos_weight': 1.0138432218309141}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:51,998] Trial 49 finished with value: 0.3375536169885188 and parameters: {'max_depth': 6, 'learning_rate': 0.23243481746509864, 'num_leaves': 64, 'min_child_samples': 103, 'subsample': 0.6017138215285667, 'colsample_bytree': 0.4782622127271712, 'scale_pos_weight': 1.1359057504334205}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:52,325] Trial 50 finished with value: 0.3367627506711724 and parameters: {'max_depth': 6, 'learning_rate': 0.1922244176078302, 'num_leaves': 64, 'min_child_samples': 143, 'subsample': 0.5830053929965406, 'colsample_bytree': 0.44716292139074953, 'scale_pos_weight': 1.2416500962851722}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:52,636] Trial 51 finished with value: 0.35661841286199425 and parameters: {'max_depth': 5, 'learning_rate': 0.2207364911409798, 'num_leaves': 32, 'min_child_samples': 107, 'subsample': 0.5346678233905847, 'colsample_bytree': 0.49551417353048166, 'scale_pos_weight': 1.0982117975765981}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:52,949] Trial 52 finished with value: 0.35050454938518333 and parameters: {'max_depth': 5, 'learning_rate': 0.11835138316921129, 'num_leaves': 32, 'min_child_samples': 102, 'subsample': 0.544914096609808, 'colsample_bytree': 0.5135203000636431, 'scale_pos_weight': 1.0848415386461274}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:53,251] Trial 53 finished with value: 0.35450150200136354 and parameters: {'max_depth': 5, 'learning_rate': 0.20619578317800966, 'num_leaves': 32, 'min_child_samples': 116, 'subsample': 0.42888291877717943, 'colsample_bytree': 0.5002074646858312, 'scale_pos_weight': 1.1850489344856128}. Best is trial 24 with value: 0.36038624557665044.
[I 2026-05-10 09:33:53,566] Trial 54 finished with value: 0.2837763743353645 and parameters: {'max_depth': 5, 'learning_rate': 0.18461050926638023, 'num_leaves': 32, 'min_child_samples': 108, 'subsample': 0.562653350790069, 'colsample_bytree': 0.48247718174732385, 'scale_pos_weight': 2.323515112696671}. Best is trial 24 with value: 0.36038624557665044.

========================================
최종 정밀 탐색 최고 PR-AUC : 0.3781
최적 파라미터 : {'max_depth': 5, 'learning_rate': 0.2498855762212911, 'num_leaves': 32, 'min_child_samples': 140, 'subsample': 0.5299175899599644, 'colsample_bytree': 0.5593990379735718, 'scale_pos_weight': 1.183426483440904}
========================================

In [ ]:
# 3차 탐색
def objective(trial):
    max_depth = trial.suggest_int('max_depth', 3, 6)   # 트리를 더 얕게 만들 수 있도록 하한선을 3으로 낮춤
    max_leaves_limit = 2 ** max_depth    # max_depth에 따라 생성 가능한 최대 잎의 수

    params = {
        'n_estimators': 2000,
        'learning_rate': trial.suggest_float('learning_rate', 0.20, 0.35),
        'max_depth': max_depth,
        'num_leaves': trial.suggest_int('num_leaves', 8, max_leaves_limit),     # 잎의 개수는 8개부터 최대 허용치까지 유연하게 탐색
        'min_child_samples': trial.suggest_int('min_child_samples', 120, 160),
        'subsample': trial.suggest_float('subsample', 0.45, 0.60),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.50, 0.65),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1.0, 1.4),
        'random_state': 42,
        'n_jobs': -1,
        'verbose': -1
    }

    model = LGBMClassifier(**params)

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        eval_metric='pr_auc',
        callbacks=[
            early_stopping(stopping_rounds=50, verbose=False),
            log_evaluation(0)
        ]
    )

    preds_proba = model.predict_proba(X_val)[:, 1]
    prauc = average_precision_score(y_val, preds_proba)

    return prauc

study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, n_trials=1000)

print("\n" + "="*40)
print(f"최고 PR-AUC : {study.best_value:.4f}")
print(f"최적 파라미터 : {study.best_params}")
print("="*40)

[I 2026-05-10 09:39:19,163] A new study created in memory with name: no-name-aa15ca62-17c6-4cc1-9b6c-d9bd623f0d12
[I 2026-05-10 09:39:19,481] Trial 0 finished with value: 0.31542607272749573 and parameters: {'max_depth': 4, 'learning_rate': 0.3426071459614874, 'num_leaves': 14, 'min_child_samples': 144, 'subsample': 0.4734027960663655, 'colsample_bytree': 0.5233991780504303, 'scale_pos_weight': 1.0232334448672797}. Best is trial 0 with value: 0.31542607272749573.
[I 2026-05-10 09:39:19,789] Trial 1 finished with value: 0.31992315301486024 and parameters: {'max_depth': 6, 'learning_rate': 0.2901672517614813, 'num_leaves': 48, 'min_child_samples': 120, 'subsample': 0.5954864778242991, 'colsample_bytree': 0.6248663961200633, 'scale_pos_weight': 1.0849356442713105}. Best is trial 1 with value: 0.31992315301486024.
[I 2026-05-10 09:39:20,033] Trial 2 finished with value: 0.3284361471457098 and parameters: {'max_depth': 3, 'learning_rate': 0.22751067647801507, 'num_leaves': 8, 'min_child_samples': 132, 'subsample': 0.5287134647448357, 'colsample_bytree': 0.5647917527963173, 'scale_pos_weight': 1.1164916560792166}. Best is trial 2 with value: 0.3284361471457098.
[I 2026-05-10 09:39:20,345] Trial 3 finished with value: 0.32744086570494074 and parameters: {'max_depth': 5, 'learning_rate': 0.2209240790978063, 'num_leaves': 15, 'min_child_samples': 135, 'subsample': 0.5184104976325554, 'colsample_bytree': 0.617776394208952, 'scale_pos_weight': 1.0798695128633438}. Best is trial 2 with value: 0.3284361471457098.
[I 2026-05-10 09:39:20,584] Trial 4 finished with value: 0.3234924807748487 and parameters: {'max_depth': 5, 'learning_rate': 0.28886218532930635, 'num_leaves': 9, 'min_child_samples': 144, 'subsample': 0.47557861855309375, 'colsample_bytree': 0.509757738947792, 'scale_pos_weight': 1.3795542149013333}. Best is trial 2 with value: 0.3284361471457098.
[I 2026-05-10 09:39:20,868] Trial 5 finished with value: 0.3138721556827955 and parameters: {'max_depth': 6, 'learning_rate': 0.3212596022174692, 'num_leaves': 25, 'min_child_samples': 124, 'subsample': 0.5526349539768235, 'colsample_bytree': 0.5660228740609402, 'scale_pos_weight': 1.0488152939379116}. Best is trial 2 with value: 0.3284361471457098.
[I 2026-05-10 09:39:21,124] Trial 6 finished with value: 0.3431127412868127 and parameters: {'max_depth': 4, 'learning_rate': 0.20515827816728277, 'num_leaves': 16, 'min_child_samples': 130, 'subsample': 0.5493783426530973, 'colsample_bytree': 0.5467566614134116, 'scale_pos_weight': 1.2080272084711243}. Best is trial 6 with value: 0.3431127412868127.
[I 2026-05-10 09:39:21,437] Trial 7 finished with value: 0.3337435599966825 and parameters: {'max_depth': 5, 'learning_rate': 0.22772816832882906, 'num_leaves': 32, 'min_child_samples': 151, 'subsample': 0.5909248412346284, 'colsample_bytree': 0.6342241025641473, 'scale_pos_weight': 1.239159991524434}. Best is trial 6 with value: 0.3431127412868127.
[I 2026-05-10 09:39:21,719] Trial 8 finished with value: 0.3425144846501545 and parameters: {'max_depth': 6, 'learning_rate': 0.21327387530778794, 'num_leaves': 19, 'min_child_samples': 121, 'subsample': 0.49879954961448963, 'colsample_bytree': 0.5583015934534223, 'scale_pos_weight': 1.1085396127095584}. Best is trial 6 with value: 0.3431127412868127.
[I 2026-05-10 09:39:22,013] Trial 9 finished with value: 0.3138181073574169 and parameters: {'max_depth': 6, 'learning_rate': 0.2535129990040384, 'num_leaves': 24, 'min_child_samples': 142, 'subsample': 0.4711386337462144, 'colsample_bytree': 0.620329547113106, 'scale_pos_weight': 1.0298202574719084}. Best is trial 6 with value: 0.3431127412868127.
[I 2026-05-10 09:39:22,266] Trial 10 finished with value: 0.32932034868936894 and parameters: {'max_depth': 3, 'learning_rate': 0.26116282547909997, 'num_leaves': 8, 'min_child_samples': 159, 'subsample': 0.5608358435075579, 'colsample_bytree': 0.5409030315801627, 'scale_pos_weight': 1.230083226726109}. Best is trial 6 with value: 0.3431127412868127.
[I 2026-05-10 09:39:22,551] Trial 11 finished with value: 0.33214689810979164 and parameters: {'max_depth': 4, 'learning_rate': 0.20095746551510013, 'num_leaves': 16, 'min_child_samples': 127, 'subsample': 0.5113691832467785, 'colsample_bytree': 0.592360556206065, 'scale_pos_weight': 1.1738316571539311}. Best is trial 6 with value: 0.3431127412868127.
[I 2026-05-10 09:39:22,820] Trial 12 finished with value: 0.33911519336653595 and parameters: {'max_depth': 4, 'learning_rate': 0.20465825162341086, 'num_leaves': 16, 'min_child_samples': 129, 'subsample': 0.49816375707893656, 'colsample_bytree': 0.5421606140475353, 'scale_pos_weight': 1.2958761780561434}. Best is trial 6 with value: 0.3431127412868127.
[I 2026-05-10 09:39:24,320] Trial 13 finished with value: 0.3321879517989229 and parameters: {'max_depth': 4, 'learning_rate': 0.24359070120508935, 'num_leaves': 13, 'min_child_samples': 122, 'subsample': 0.5441464417883924, 'colsample_bytree': 0.5871436373650325, 'scale_pos_weight': 1.1640718558137357}. Best is trial 6 with value: 0.3431127412868127.
[I 2026-05-10 09:39:26,205] Trial 14 finished with value: 0.3548206928701767 and parameters: {'max_depth': 5, 'learning_rate': 0.21611264020661805, 'num_leaves': 21, 'min_child_samples': 136, 'subsample': 0.45145495576693284, 'colsample_bytree': 0.545224288655972, 'scale_pos_weight': 1.1356056577882385}. Best is trial 14 with value: 0.3548206928701767.
[I 2026-05-10 09:39:26,501] Trial 15 finished with value: 0.3618692052820994 and parameters: {'max_depth': 5, 'learning_rate': 0.23948467279462038, 'num_leaves': 23, 'min_child_samples': 135, 'subsample': 0.4538701462135656, 'colsample_bytree': 0.500886023554024, 'scale_pos_weight': 1.2871305948023237}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:26,794] Trial 16 finished with value: 0.352977187383128 and parameters: {'max_depth': 5, 'learning_rate': 0.24326604070160418, 'num_leaves': 25, 'min_child_samples': 137, 'subsample': 0.4537612707763658, 'colsample_bytree': 0.5051244241027443, 'scale_pos_weight': 1.2952789649540777}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:27,074] Trial 17 finished with value: 0.3257428144928926 and parameters: {'max_depth': 5, 'learning_rate': 0.2672822085335114, 'num_leaves': 21, 'min_child_samples': 150, 'subsample': 0.45042966663648815, 'colsample_bytree': 0.5267429743491802, 'scale_pos_weight': 1.3632012099488806}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:27,367] Trial 18 finished with value: 0.35263007647584177 and parameters: {'max_depth': 5, 'learning_rate': 0.2381492550898261, 'num_leaves': 30, 'min_child_samples': 139, 'subsample': 0.48888871622335184, 'colsample_bytree': 0.5000831576853751, 'scale_pos_weight': 1.2907859007152178}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:27,710] Trial 19 finished with value: 0.3105532124824533 and parameters: {'max_depth': 6, 'learning_rate': 0.2852915395468557, 'num_leaves': 42, 'min_child_samples': 135, 'subsample': 0.4612341997098921, 'colsample_bytree': 0.5229882251334165, 'scale_pos_weight': 1.1509376605388808}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:28,004] Trial 20 finished with value: 0.3274153084606565 and parameters: {'max_depth': 5, 'learning_rate': 0.27580819302503257, 'num_leaves': 21, 'min_child_samples': 148, 'subsample': 0.4896105549693555, 'colsample_bytree': 0.5847580927344065, 'scale_pos_weight': 1.252319783127}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:28,296] Trial 21 finished with value: 0.3530732220755535 and parameters: {'max_depth': 5, 'learning_rate': 0.24457704738946254, 'num_leaves': 25, 'min_child_samples': 137, 'subsample': 0.45290874530638225, 'colsample_bytree': 0.5003557971693001, 'scale_pos_weight': 1.3298528902087923}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:28,594] Trial 22 finished with value: 0.36029872371518407 and parameters: {'max_depth': 5, 'learning_rate': 0.2336387063177137, 'num_leaves': 23, 'min_child_samples': 133, 'subsample': 0.46224860382378674, 'colsample_bytree': 0.5153539652280665, 'scale_pos_weight': 1.346961593953737}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:28,878] Trial 23 finished with value: 0.3610138401154296 and parameters: {'max_depth': 5, 'learning_rate': 0.2292812526249871, 'num_leaves': 19, 'min_child_samples': 134, 'subsample': 0.4673734678428638, 'colsample_bytree': 0.5186570468434427, 'scale_pos_weight': 1.3412652858837373}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:29,141] Trial 24 finished with value: 0.32256885007246366 and parameters: {'max_depth': 4, 'learning_rate': 0.23402672956106754, 'num_leaves': 11, 'min_child_samples': 132, 'subsample': 0.46955671144132827, 'colsample_bytree': 0.518532259497195, 'scale_pos_weight': 1.3958354481482587}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:29,428] Trial 25 finished with value: 0.3592111296573722 and parameters: {'max_depth': 5, 'learning_rate': 0.25526304412157597, 'num_leaves': 19, 'min_child_samples': 127, 'subsample': 0.48110417021564345, 'colsample_bytree': 0.5300902759861368, 'scale_pos_weight': 1.3266304310951818}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:29,806] Trial 26 finished with value: 0.32436889067946517 and parameters: {'max_depth': 6, 'learning_rate': 0.22556529491126198, 'num_leaves': 39, 'min_child_samples': 132, 'subsample': 0.4641546388818219, 'colsample_bytree': 0.5105964671513087, 'scale_pos_weight': 1.3477529508352402}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:30,089] Trial 27 finished with value: 0.3209255032687275 and parameters: {'max_depth': 5, 'learning_rate': 0.3002125814739265, 'num_leaves': 23, 'min_child_samples': 139, 'subsample': 0.5012028236961764, 'colsample_bytree': 0.5143087234552628, 'scale_pos_weight': 1.2839293113637762}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:30,355] Trial 28 finished with value: 0.3233223097879985 and parameters: {'max_depth': 4, 'learning_rate': 0.25045413511399156, 'num_leaves': 11, 'min_child_samples': 125, 'subsample': 0.48441515559635345, 'colsample_bytree': 0.5324311135710488, 'scale_pos_weight': 1.325002810902495}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:30,619] Trial 29 finished with value: 0.3302908230319088 and parameters: {'max_depth': 4, 'learning_rate': 0.26819701350607994, 'num_leaves': 13, 'min_child_samples': 144, 'subsample': 0.46793215515156344, 'colsample_bytree': 0.518513138767966, 'scale_pos_weight': 1.2599331439248975}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:30,933] Trial 30 finished with value: 0.32119248359145663 and parameters: {'max_depth': 6, 'learning_rate': 0.34406689700245785, 'num_leaves': 30, 'min_child_samples': 140, 'subsample': 0.5766068257254492, 'colsample_bytree': 0.6043605217252404, 'scale_pos_weight': 1.3715641898240485}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:31,226] Trial 31 finished with value: 0.35949321677039575 and parameters: {'max_depth': 5, 'learning_rate': 0.2534596232456269, 'num_leaves': 18, 'min_child_samples': 128, 'subsample': 0.4778644834159427, 'colsample_bytree': 0.5323832062890412, 'scale_pos_weight': 1.3265169172626217}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:31,513] Trial 32 finished with value: 0.35575696273928914 and parameters: {'max_depth': 5, 'learning_rate': 0.23531277278320495, 'num_leaves': 18, 'min_child_samples': 133, 'subsample': 0.47634760426370726, 'colsample_bytree': 0.5341575001778568, 'scale_pos_weight': 1.3448119944935426}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:31,843] Trial 33 finished with value: 0.35669516634926424 and parameters: {'max_depth': 5, 'learning_rate': 0.23133689175904087, 'num_leaves': 23, 'min_child_samples': 129, 'subsample': 0.4600032270184194, 'colsample_bytree': 0.5535223474971174, 'scale_pos_weight': 1.3093271737509018}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:32,128] Trial 34 finished with value: 0.3596111214620634 and parameters: {'max_depth': 5, 'learning_rate': 0.21832230159824545, 'num_leaves': 18, 'min_child_samples': 134, 'subsample': 0.45834685398808384, 'colsample_bytree': 0.5119288350884273, 'scale_pos_weight': 1.2700880260784975}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:32,423] Trial 35 finished with value: 0.3505413768414195 and parameters: {'max_depth': 5, 'learning_rate': 0.21461464502233896, 'num_leaves': 22, 'min_child_samples': 133, 'subsample': 0.4595639698231541, 'colsample_bytree': 0.5110301316262658, 'scale_pos_weight': 1.2668899916421335}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:32,720] Trial 36 finished with value: 0.35084935786913823 and parameters: {'max_depth': 5, 'learning_rate': 0.2241391844867237, 'num_leaves': 27, 'min_child_samples': 134, 'subsample': 0.532739092088787, 'colsample_bytree': 0.5216001483146075, 'scale_pos_weight': 1.222147114248045}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:32,960] Trial 37 finished with value: 0.3298967627302042 and parameters: {'max_depth': 3, 'learning_rate': 0.32823886330917385, 'num_leaves': 8, 'min_child_samples': 141, 'subsample': 0.5109229116730408, 'colsample_bytree': 0.5066791549503703, 'scale_pos_weight': 1.3911957339347465}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:33,298] Trial 38 finished with value: 0.3147962061523101 and parameters: {'max_depth': 6, 'learning_rate': 0.21855758253913082, 'num_leaves': 56, 'min_child_samples': 137, 'subsample': 0.4661427013996427, 'colsample_bytree': 0.5720490261620488, 'scale_pos_weight': 1.2004021304815935}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:33,616] Trial 39 finished with value: 0.3163922514277657 and parameters: {'max_depth': 6, 'learning_rate': 0.2078764146712539, 'num_leaves': 34, 'min_child_samples': 130, 'subsample': 0.45883155542686027, 'colsample_bytree': 0.6493530646222884, 'scale_pos_weight': 1.2757970642090863}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:33,934] Trial 40 finished with value: 0.3581222329734787 and parameters: {'max_depth': 5, 'learning_rate': 0.22333559733657904, 'num_leaves': 18, 'min_child_samples': 131, 'subsample': 0.4886514598564467, 'colsample_bytree': 0.5151096061722553, 'scale_pos_weight': 1.3538920501156997}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:34,220] Trial 41 finished with value: 0.35501927296070324 and parameters: {'max_depth': 5, 'learning_rate': 0.2391818896278949, 'num_leaves': 18, 'min_child_samples': 127, 'subsample': 0.47781977771462625, 'colsample_bytree': 0.5324499694279391, 'scale_pos_weight': 1.3283314339222874}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:34,520] Trial 42 finished with value: 0.36053344846888696 and parameters: {'max_depth': 5, 'learning_rate': 0.2509293572039719, 'num_leaves': 20, 'min_child_samples': 124, 'subsample': 0.4756791517766497, 'colsample_bytree': 0.5234408817312673, 'scale_pos_weight': 1.3110167239659545}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:34,813] Trial 43 finished with value: 0.35872948117170156 and parameters: {'max_depth': 5, 'learning_rate': 0.22964819723175692, 'num_leaves': 20, 'min_child_samples': 123, 'subsample': 0.4697369702120734, 'colsample_bytree': 0.5058070651329889, 'scale_pos_weight': 1.3099009600126719}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:35,105] Trial 44 finished with value: 0.36122282361992575 and parameters: {'max_depth': 5, 'learning_rate': 0.2100933391613997, 'num_leaves': 20, 'min_child_samples': 125, 'subsample': 0.47284575847049903, 'colsample_bytree': 0.5535379294476515, 'scale_pos_weight': 1.2418054916866987}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:35,377] Trial 45 finished with value: 0.3429158066745621 and parameters: {'max_depth': 4, 'learning_rate': 0.21049850723680572, 'num_leaves': 15, 'min_child_samples': 120, 'subsample': 0.49571372287272264, 'colsample_bytree': 0.552455664802847, 'scale_pos_weight': 1.237009815224527}. Best is trial 15 with value: 0.3618692052820994.
[I 2026-05-10 09:39:35,660] Trial 46 finished with value: 0.3680889476074258 and parameters: {'max_depth': 5, 'learning_rate': 0.25916169825352653, 'num_leaves': 20, 'min_child_samples': 125, 'subsample': 0.4840803453674288, 'colsample_bytree': 0.5385923313445617, 'scale_pos_weight': 1.3813787956906842}. Best is trial 46 with value: 0.3680889476074258.
[I 2026-05-10 09:39:35,972] Trial 47 finished with value: 0.32528863195703017 and parameters: {'max_depth': 5, 'learning_rate': 0.2762314866946287, 'num_leaves': 20, 'min_child_samples': 125, 'subsample': 0.4733842980335115, 'colsample_bytree': 0.5618919233125935, 'scale_pos_weight': 1.3849250395956374}. Best is trial 46 with value: 0.3680889476074258.
[I 2026-05-10 09:39:36,281] Trial 48 finished with value: 0.318129175635772 and parameters: {'max_depth': 6, 'learning_rate': 0.2627447044121695, 'num_leaves': 28, 'min_child_samples': 124, 'subsample': 0.5091551776235917, 'colsample_bytree': 0.5409237314926207, 'scale_pos_weight': 1.3713391363841003}. Best is trial 46 with value: 0.3680889476074258.
[I 2026-05-10 09:39:39,457] Trial 49 finished with value: 0.35921888783800937 and parameters: {'max_depth': 5, 'learning_rate': 0.20050409929835206, 'num_leaves': 20, 'min_child_samples': 121, 'subsample': 0.481498522192303, 'colsample_bytree': 0.5512417265304441, 'scale_pos_weight': 1.2159197427718993}. Best is trial 46 with value: 0.3680889476074258.
[I 2026-05-10 09:39:39,731] Trial 50 finished with value: 0.32983966431607087 and parameters: {'max_depth': 4, 'learning_rate': 0.24772337244285622, 'num_leaves': 15, 'min_child_samples': 126, 'subsample': 0.518646182914822, 'colsample_bytree': 0.5679403850695767, 'scale_pos_weight': 1.3091053911980675}. Best is trial 46 with value: 0.3680889476074258.
[I 2026-05-10 09:39:40,017] Trial 51 finished with value: 0.3875586579712136 and parameters: {'max_depth': 5, 'learning_rate': 0.2583200133036465, 'num_leaves': 23, 'min_child_samples': 123, 'subsample': 0.4723819736562826, 'colsample_bytree': 0.527312057690891, 'scale_pos_weight': 1.3482513749592426}. Best is trial 51 with value: 0.3875586579712136.
[I 2026-05-10 09:39:40,300] Trial 52 finished with value: 0.32652445983769346 and parameters: {'max_depth': 5, 'learning_rate': 0.282678050984128, 'num_leaves': 24, 'min_child_samples': 122, 'subsample': 0.49230486343022456, 'colsample_bytree': 0.5380247217028165, 'scale_pos_weight': 1.3623448006639904}. Best is trial 51 with value: 0.3875586579712136.
[I 2026-05-10 09:39:40,653] Trial 53 finished with value: 0.36060677840258193 and parameters: {'max_depth': 5, 'learning_rate': 0.25561070588101564, 'num_leaves': 22, 'min_child_samples': 123, 'subsample': 0.4738799004051383, 'colsample_bytree': 0.5230913346588211, 'scale_pos_weight': 1.187109949514779}. Best is trial 51 with value: 0.3875586579712136.
[I 2026-05-10 09:39:40,943] Trial 54 finished with value: 0.3603235677118178 and parameters: {'max_depth': 5, 'learning_rate': 0.2582268233449547, 'num_leaves': 22, 'min_child_samples': 120, 'subsample': 0.48547403045004245, 'colsample_bytree': 0.5257977858920588, 'scale_pos_weight': 1.1831692875016648}. Best is trial 51 with value: 0.3875586579712136.
[I 2026-05-10 09:39:41,258] Trial 55 finished with value: 0.3746524156971399 and parameters: {'max_depth': 5, 'learning_rate': 0.29951265999599086, 'num_leaves': 22, 'min_child_samples': 122, 'subsample': 0.5056014656177459, 'colsample_bytree': 0.5463571795535874, 'scale_pos_weight': 1.1157242320584533}. Best is trial 51 with value: 0.3875586579712136.

========================================
최고 PR-AUC : 0.4106
최적 파라미터 : {'max_depth': 5, 'learning_rate': 0.3471822878189745, 'num_leaves': 23, 'min_child_samples': 144, 'subsample': 0.5111636910456923, 'colsample_bytree': 0.5646394676662235, 'scale_pos_weight': 1.0061636591457408}
========================================

In [ ]:
# 4차 탐색
def objective(trial):
    max_depth = trial.suggest_int('max_depth', 4, 6)
    max_leaves_limit = 2 ** max_depth

    params = {
        'n_estimators': 2000,
        'learning_rate': trial.suggest_float('learning_rate', 0.25, 0.45),
        'max_depth': max_depth,
        'num_leaves': trial.suggest_int('num_leaves', 15, max_leaves_limit),
        'min_child_samples': trial.suggest_int('min_child_samples', 130, 155),
        'subsample': trial.suggest_float('subsample', 0.45, 0.55),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.50, 0.60),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 0.9, 1.1),
        'random_state': 42,
        'n_jobs': -1,
        'verbose': -1
    }

    model = LGBMClassifier(**params)

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        eval_metric='pr_auc',
        callbacks=[
            early_stopping(stopping_rounds=50, verbose=False),
            log_evaluation(0)
        ]
    )

    preds_proba = model.predict_proba(X_val)[:, 1]
    prauc = average_precision_score(y_val, preds_proba)

    return prauc

study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, n_trials=1500)

print("\n" + "="*40)
print(f"최고 PR-AUC : {study.best_value:.4f}")
print(f"최적 파라미터 : {study.best_params}")
print("="*40)

[I 2026-05-10 09:48:32,740] A new study created in memory with name: no-name-760ff073-653d-467d-bad9-81cf5cad4735
[I 2026-05-10 09:48:33,014] Trial 0 finished with value: 0.3477369601587254 and parameters: {'max_depth': 5, 'learning_rate': 0.4401428612819832, 'num_leaves': 28, 'min_child_samples': 145, 'subsample': 0.46560186404424364, 'colsample_bytree': 0.5155994520336202, 'scale_pos_weight': 0.9116167224336399}. Best is trial 0 with value: 0.3477369601587254.
[I 2026-05-10 09:48:33,325] Trial 1 finished with value: 0.33032821156207 and parameters: {'max_depth': 6, 'learning_rate': 0.37022300234864175, 'num_leaves': 50, 'min_child_samples': 130, 'subsample': 0.5469909852161995, 'colsample_bytree': 0.5832442640800422, 'scale_pos_weight': 0.9424678221356553}. Best is trial 0 with value: 0.3477369601587254.
[I 2026-05-10 09:48:33,582] Trial 2 finished with value: 0.34564272927703743 and parameters: {'max_depth': 4, 'learning_rate': 0.28668090197068674, 'num_leaves': 15, 'min_child_samples': 143, 'subsample': 0.4931945018642116, 'colsample_bytree': 0.5291229140198042, 'scale_pos_weight': 1.022370578944476}. Best is trial 0 with value: 0.3477369601587254.
[I 2026-05-10 09:48:33,880] Trial 3 finished with value: 0.350501345526102 and parameters: {'max_depth': 4, 'learning_rate': 0.3084289297070436, 'num_leaves': 15, 'min_child_samples': 141, 'subsample': 0.5285175961393014, 'colsample_bytree': 0.5199673782158359, 'scale_pos_weight': 1.0028468876827223}. Best is trial 3 with value: 0.350501345526102.
[I 2026-05-10 09:48:37,107] Trial 4 finished with value: 0.3258405107703968 and parameters: {'max_depth': 5, 'learning_rate': 0.25929008254399954, 'num_leaves': 25, 'min_child_samples': 134, 'subsample': 0.456505159298528, 'colsample_bytree': 0.5948885537253333, 'scale_pos_weight': 1.093126406614912}. Best is trial 3 with value: 0.350501345526102.
[I 2026-05-10 09:48:37,408] Trial 5 finished with value: 0.3134228354070584 and parameters: {'max_depth': 6, 'learning_rate': 0.31092275383467416, 'num_leaves': 19, 'min_child_samples': 147, 'subsample': 0.49401524937396013, 'colsample_bytree': 0.5122038234844779, 'scale_pos_weight': 0.9990353820222541}. Best is trial 3 with value: 0.350501345526102.
[I 2026-05-10 09:48:37,654] Trial 6 finished with value: 0.31521958731377475 and parameters: {'max_depth': 4, 'learning_rate': 0.4318640804157564, 'num_leaves': 15, 'min_child_samples': 147, 'subsample': 0.4811711076089411, 'colsample_bytree': 0.5520068021177811, 'scale_pos_weight': 1.0093420558686559}. Best is trial 3 with value: 0.350501345526102.
[I 2026-05-10 09:48:37,908] Trial 7 finished with value: 0.3154205222396883 and parameters: {'max_depth': 4, 'learning_rate': 0.44391692555291173, 'num_leaves': 16, 'min_child_samples': 154, 'subsample': 0.5394827350427649, 'colsample_bytree': 0.5597899978811085, 'scale_pos_weight': 1.0843748470046235}. Best is trial 3 with value: 0.350501345526102.
[I 2026-05-10 09:48:38,164] Trial 8 finished with value: 0.3470681626640276 and parameters: {'max_depth': 4, 'learning_rate': 0.289196572483829, 'num_leaves': 15, 'min_child_samples': 138, 'subsample': 0.4888677289689482, 'colsample_bytree': 0.5271349031773895, 'scale_pos_weight': 1.065747501830386}. Best is trial 3 with value: 0.350501345526102.
[I 2026-05-10 09:48:38,458] Trial 9 finished with value: 0.37730767249334557 and parameters: {'max_depth': 5, 'learning_rate': 0.30618690193747616, 'num_leaves': 24, 'min_child_samples': 133, 'subsample': 0.530219698075404, 'colsample_bytree': 0.507455064367977, 'scale_pos_weight': 1.0973773873201036}. Best is trial 9 with value: 0.37730767249334557.
[I 2026-05-10 09:48:38,747] Trial 10 finished with value: 0.3738737673916358 and parameters: {'max_depth': 5, 'learning_rate': 0.3615272607126992, 'num_leaves': 30, 'min_child_samples': 130, 'subsample': 0.5183107242717947, 'colsample_bytree': 0.5038725199961183, 'scale_pos_weight': 1.046073379041402}. Best is trial 9 with value: 0.37730767249334557.
[I 2026-05-10 09:48:39,038] Trial 11 finished with value: 0.3736916044236864 and parameters: {'max_depth': 5, 'learning_rate': 0.36410957297633667, 'num_leaves': 31, 'min_child_samples': 130, 'subsample': 0.5177204414743941, 'colsample_bytree': 0.5023514775597598, 'scale_pos_weight': 1.044536070579006}. Best is trial 9 with value: 0.37730767249334557.
[I 2026-05-10 09:48:39,327] Trial 12 finished with value: 0.38680905286896117 and parameters: {'max_depth': 5, 'learning_rate': 0.3904710920280004, 'num_leaves': 32, 'min_child_samples': 135, 'subsample': 0.514821187170902, 'colsample_bytree': 0.5003911124190054, 'scale_pos_weight': 1.0582938664499906}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:39,636] Trial 13 finished with value: 0.3121565868641119 and parameters: {'max_depth': 6, 'learning_rate': 0.39519809670661044, 'num_leaves': 40, 'min_child_samples': 137, 'subsample': 0.5105671942573949, 'colsample_bytree': 0.539363103264633, 'scale_pos_weight': 1.0992033063494873}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:39,919] Trial 14 finished with value: 0.32380159403814524 and parameters: {'max_depth': 5, 'learning_rate': 0.39869164310226923, 'num_leaves': 22, 'min_child_samples': 135, 'subsample': 0.5314783719004899, 'colsample_bytree': 0.5663406428611982, 'scale_pos_weight': 1.061915783670623}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:40,206] Trial 15 finished with value: 0.38143240146715274 and parameters: {'max_depth': 5, 'learning_rate': 0.3230787790071699, 'num_leaves': 24, 'min_child_samples': 134, 'subsample': 0.5060745930547139, 'colsample_bytree': 0.5367378887220016, 'scale_pos_weight': 0.965486006118581}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:40,549] Trial 16 finished with value: 0.3578811977344506 and parameters: {'max_depth': 5, 'learning_rate': 0.33329074626565125, 'num_leaves': 27, 'min_child_samples': 140, 'subsample': 0.5065025096109737, 'colsample_bytree': 0.5406786007831761, 'scale_pos_weight': 0.9662811981414089}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:40,861] Trial 17 finished with value: 0.3200131735909754 and parameters: {'max_depth': 6, 'learning_rate': 0.33942609258867873, 'num_leaves': 38, 'min_child_samples': 137, 'subsample': 0.4777950414355898, 'colsample_bytree': 0.574251253020482, 'scale_pos_weight': 0.9730451063759575}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:41,168] Trial 18 finished with value: 0.3100097151400042 and parameters: {'max_depth': 6, 'learning_rate': 0.40980773766932405, 'num_leaves': 37, 'min_child_samples': 152, 'subsample': 0.5048073307616918, 'colsample_bytree': 0.5398359077364645, 'scale_pos_weight': 0.9026358428761847}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:41,490] Trial 19 finished with value: 0.3464574947983281 and parameters: {'max_depth': 5, 'learning_rate': 0.252691750396367, 'num_leaves': 21, 'min_child_samples': 133, 'subsample': 0.5176378266220533, 'colsample_bytree': 0.5224887696490609, 'scale_pos_weight': 0.9359619324886704}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:41,764] Trial 20 finished with value: 0.3492406635197509 and parameters: {'max_depth': 5, 'learning_rate': 0.3842473934701104, 'num_leaves': 18, 'min_child_samples': 139, 'subsample': 0.4737696987661098, 'colsample_bytree': 0.5323186444431993, 'scale_pos_weight': 0.9788113758692106}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:42,051] Trial 21 finished with value: 0.3781763391560449 and parameters: {'max_depth': 5, 'learning_rate': 0.3284576251438834, 'num_leaves': 24, 'min_child_samples': 133, 'subsample': 0.5297497850446368, 'colsample_bytree': 0.5099568644739572, 'scale_pos_weight': 1.075900159177614}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:42,334] Trial 22 finished with value: 0.3719766056159211 and parameters: {'max_depth': 5, 'learning_rate': 0.32967441937748554, 'num_leaves': 26, 'min_child_samples': 135, 'subsample': 0.5231058898804332, 'colsample_bytree': 0.5129108406408694, 'scale_pos_weight': 1.0306804693509317}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:42,664] Trial 23 finished with value: 0.3812853881517136 and parameters: {'max_depth': 5, 'learning_rate': 0.34874230530179395, 'num_leaves': 22, 'min_child_samples': 133, 'subsample': 0.5394003124875302, 'colsample_bytree': 0.5070296361966371, 'scale_pos_weight': 1.074077642764638}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:42,947] Trial 24 finished with value: 0.3823445269129575 and parameters: {'max_depth': 5, 'learning_rate': 0.3490248526433078, 'num_leaves': 22, 'min_child_samples': 136, 'subsample': 0.5482911807589633, 'colsample_bytree': 0.5001317331436641, 'scale_pos_weight': 1.050952607211299}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:43,219] Trial 25 finished with value: 0.3239712421099983 and parameters: {'max_depth': 5, 'learning_rate': 0.4233727908328729, 'num_leaves': 20, 'min_child_samples': 136, 'subsample': 0.546960486382511, 'colsample_bytree': 0.5218649878034702, 'scale_pos_weight': 1.0462216625079148}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:43,620] Trial 26 finished with value: 0.31427811363402036 and parameters: {'max_depth': 6, 'learning_rate': 0.37633685295689323, 'num_leaves': 34, 'min_child_samples': 143, 'subsample': 0.5018753718564002, 'colsample_bytree': 0.548342083919505, 'scale_pos_weight': 0.9494690546185905}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:43,885] Trial 27 finished with value: 0.3137059372686706 and parameters: {'max_depth': 4, 'learning_rate': 0.34935244978574465, 'num_leaves': 16, 'min_child_samples': 141, 'subsample': 0.5098907433186411, 'colsample_bytree': 0.5014393920293276, 'scale_pos_weight': 0.9882434149514533}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:44,167] Trial 28 finished with value: 0.3309472202133368 and parameters: {'max_depth': 5, 'learning_rate': 0.4120363214439263, 'num_leaves': 23, 'min_child_samples': 132, 'subsample': 0.48641250130413477, 'colsample_bytree': 0.5508356540020138, 'scale_pos_weight': 1.023918880594901}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:44,447] Trial 29 finished with value: 0.3507125551632172 and parameters: {'max_depth': 5, 'learning_rate': 0.39136658574199296, 'num_leaves': 28, 'min_child_samples': 138, 'subsample': 0.46234209251197733, 'colsample_bytree': 0.5163295241929224, 'scale_pos_weight': 0.9230384894492549}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:44,731] Trial 30 finished with value: 0.341214682221748 and parameters: {'max_depth': 5, 'learning_rate': 0.31826547391869614, 'num_leaves': 18, 'min_child_samples': 145, 'subsample': 0.49617824446759073, 'colsample_bytree': 0.5000262112304713, 'scale_pos_weight': 0.9628485845820164}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:45,014] Trial 31 finished with value: 0.38203026409159335 and parameters: {'max_depth': 5, 'learning_rate': 0.3479057624152841, 'num_leaves': 22, 'min_child_samples': 131, 'subsample': 0.5392955669800363, 'colsample_bytree': 0.5086183323576648, 'scale_pos_weight': 1.0605289676809138}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:45,292] Trial 32 finished with value: 0.32522515050439016 and parameters: {'max_depth': 5, 'learning_rate': 0.36080858150466233, 'num_leaves': 21, 'min_child_samples': 131, 'subsample': 0.5394360661898565, 'colsample_bytree': 0.5155073907509301, 'scale_pos_weight': 1.056682463023815}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:45,635] Trial 33 finished with value: 0.37925692066237715 and parameters: {'max_depth': 5, 'learning_rate': 0.3436462193561044, 'num_leaves': 22, 'min_child_samples': 135, 'subsample': 0.5472597450896041, 'colsample_bytree': 0.5328514917575797, 'scale_pos_weight': 1.0348669630919447}. Best is trial 12 with value: 0.38680905286896117.
[I 2026-05-10 09:48:45,922] Trial 34 finished with value: 0.3941973676039476 and parameters: {'max_depth': 5, 'learning_rate': 0.3753150270381969, 'num_leaves': 25, 'min_child_samples': 131, 'subsample': 0.548635990163322, 'colsample_bytree': 0.5252833658188096, 'scale_pos_weight': 1.0135892054480986}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:46,206] Trial 35 finished with value: 0.34577064331069823 and parameters: {'max_depth': 5, 'learning_rate': 0.37713571471191165, 'num_leaves': 26, 'min_child_samples': 131, 'subsample': 0.5498202334169261, 'colsample_bytree': 0.5178849874670343, 'scale_pos_weight': 1.0127624424974262}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:46,466] Trial 36 finished with value: 0.31361329785044767 and parameters: {'max_depth': 4, 'learning_rate': 0.36735288904272856, 'num_leaves': 15, 'min_child_samples': 131, 'subsample': 0.5361052927990189, 'colsample_bytree': 0.5089348803678059, 'scale_pos_weight': 1.0542064061220755}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:46,814] Trial 37 finished with value: 0.311564999919929 and parameters: {'max_depth': 6, 'learning_rate': 0.4058887490512359, 'num_leaves': 45, 'min_child_samples': 132, 'subsample': 0.5454971102962569, 'colsample_bytree': 0.5257439708123696, 'scale_pos_weight': 1.034528203189053}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:47,117] Trial 38 finished with value: 0.3133364966610311 and parameters: {'max_depth': 4, 'learning_rate': 0.38432390305385733, 'num_leaves': 15, 'min_child_samples': 136, 'subsample': 0.5423974266361126, 'colsample_bytree': 0.5061287565151965, 'scale_pos_weight': 1.0820598146395817}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:49,964] Trial 39 finished with value: 0.38243532638808064 and parameters: {'max_depth': 5, 'learning_rate': 0.2912705385792179, 'num_leaves': 20, 'min_child_samples': 130, 'subsample': 0.5241200037483884, 'colsample_bytree': 0.5001136381244479, 'scale_pos_weight': 1.015638143318674}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:50,499] Trial 40 finished with value: 0.33229295300348194 and parameters: {'max_depth': 5, 'learning_rate': 0.275869208208896, 'num_leaves': 19, 'min_child_samples': 130, 'subsample': 0.5354832718754601, 'colsample_bytree': 0.5860607568592842, 'scale_pos_weight': 0.9939251430288618}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:50,823] Trial 41 finished with value: 0.38548019482996054 and parameters: {'max_depth': 5, 'learning_rate': 0.2981546786942092, 'num_leaves': 20, 'min_child_samples': 132, 'subsample': 0.5243855436048996, 'colsample_bytree': 0.5132310515945944, 'scale_pos_weight': 1.014619161639874}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:51,117] Trial 42 finished with value: 0.3606312580217382 and parameters: {'max_depth': 5, 'learning_rate': 0.29462235199021114, 'num_leaves': 20, 'min_child_samples': 134, 'subsample': 0.5239113849321521, 'colsample_bytree': 0.5002667961277282, 'scale_pos_weight': 1.0142103094239052}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:51,403] Trial 43 finished with value: 0.38315682346626984 and parameters: {'max_depth': 5, 'learning_rate': 0.26775054664863807, 'num_leaves': 19, 'min_child_samples': 132, 'subsample': 0.52508324125998, 'colsample_bytree': 0.5121318974551613, 'scale_pos_weight': 1.0041862224865572}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:51,689] Trial 44 finished with value: 0.3686514046446945 and parameters: {'max_depth': 5, 'learning_rate': 0.2721978143178417, 'num_leaves': 17, 'min_child_samples': 132, 'subsample': 0.5234986918033431, 'colsample_bytree': 0.5135006921872478, 'scale_pos_weight': 1.004838524127288}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:51,986] Trial 45 finished with value: 0.3620516367768961 and parameters: {'max_depth': 4, 'learning_rate': 0.2675703490605536, 'num_leaves': 15, 'min_child_samples': 130, 'subsample': 0.5127189501853703, 'colsample_bytree': 0.5246068281352209, 'scale_pos_weight': 1.01966359833792}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:52,271] Trial 46 finished with value: 0.35754164444138636 and parameters: {'max_depth': 5, 'learning_rate': 0.2975210072608291, 'num_leaves': 19, 'min_child_samples': 132, 'subsample': 0.5265231456468177, 'colsample_bytree': 0.5196939929795724, 'scale_pos_weight': 0.9850390069769821}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:52,559] Trial 47 finished with value: 0.3657887117039563 and parameters: {'max_depth': 5, 'learning_rate': 0.2819234734205742, 'num_leaves': 20, 'min_child_samples': 134, 'subsample': 0.5158136622853018, 'colsample_bytree': 0.5050840636841756, 'scale_pos_weight': 0.9956703089455937}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:52,910] Trial 48 finished with value: 0.3611796557897812 and parameters: {'max_depth': 5, 'learning_rate': 0.2628662577556941, 'num_leaves': 18, 'min_child_samples': 130, 'subsample': 0.5338265281977521, 'colsample_bytree': 0.5117366481620369, 'scale_pos_weight': 1.0040414756014344}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:53,188] Trial 49 finished with value: 0.3789518147396123 and parameters: {'max_depth': 5, 'learning_rate': 0.3100623035112169, 'num_leaves': 17, 'min_child_samples': 133, 'subsample': 0.5199622346857051, 'colsample_bytree': 0.5299328085112651, 'scale_pos_weight': 1.0391959954193903}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:53,510] Trial 50 finished with value: 0.3461180081852912 and parameters: {'max_depth': 6, 'learning_rate': 0.3018851125911509, 'num_leaves': 61, 'min_child_samples': 145, 'subsample': 0.5140729480542086, 'colsample_bytree': 0.5448535392810254, 'scale_pos_weight': 1.0251057819360352}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:53,802] Trial 51 finished with value: 0.37940148220565456 and parameters: {'max_depth': 5, 'learning_rate': 0.28118847771372063, 'num_leaves': 21, 'min_child_samples': 136, 'subsample': 0.5279070249725544, 'colsample_bytree': 0.5054978313821149, 'scale_pos_weight': 1.0175250947316297}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:54,115] Trial 52 finished with value: 0.37436386455022147 and parameters: {'max_depth': 5, 'learning_rate': 0.25563776784153847, 'num_leaves': 23, 'min_child_samples': 149, 'subsample': 0.5217004591716928, 'colsample_bytree': 0.5029675497110958, 'scale_pos_weight': 1.0494957758596837}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:54,396] Trial 53 finished with value: 0.3832165695955543 and parameters: {'max_depth': 5, 'learning_rate': 0.2899662838394723, 'num_leaves': 20, 'min_child_samples': 135, 'subsample': 0.5326769433279908, 'colsample_bytree': 0.5109974693859775, 'scale_pos_weight': 1.0672402465813482}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:54,690] Trial 54 finished with value: 0.3662409619058339 and parameters: {'max_depth': 5, 'learning_rate': 0.28693734201693344, 'num_leaves': 20, 'min_child_samples': 135, 'subsample': 0.5317821523473233, 'colsample_bytree': 0.5180184268872567, 'scale_pos_weight': 1.0715633380658043}. Best is trial 34 with value: 0.3941973676039476.
[I 2026-05-10 09:48:55,017] Trial 55 finished with value: 0.3571750425834691 and parameters: {'max_depth': 5, 'learning_rate': 0.29203273869650315, 'num_leaves': 19, 'min_child_samples': 138, 'subsample': 0.5257355795211288, 'colsample_bytree': 0.5119999875620334, 'scale_pos_weight': 1.008352366109511}. Best is trial 34 with value: 0.3941973676039476.

========================================
최고 PR-AUC : 0.3951
최적 파라미터 : {'max_depth': 5, 'learning_rate': 0.34356902610511464, 'num_leaves': 27, 'min_child_samples': 135, 'subsample': 0.5382177568191784, 'colsample_bytree': 0.5466675849154781, 'scale_pos_weight': 0.9767207219327285}
========================================

- 최고 PR-AUC : 0.4106
- 최적 파라미터 : {'max_depth': 5, 'learning_rate': 0.3471822878189745, 'num_leaves': 23, 'min_child_samples': 144, 'subsample': 0.5111636910456923, 'colsample_bytree': 0.5646394676662235, 'scale_pos_weight': 1.0061636591457408}

#### auc 기준 하이퍼파라미터 튜닝

In [ ]:
def objective_auc(trial):

    max_depth = trial.suggest_int('max_depth', 4, 10)
    max_leaves_limit = min(2 ** max_depth, 256)

    params = {
        'n_estimators': 2000,
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'max_depth': max_depth,
        'num_leaves': trial.suggest_int('num_leaves', 15, max_leaves_limit),
        'min_child_samples': trial.suggest_int('min_child_samples', 20, 160),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1.0, 5.0),
        'random_state': 42,
        'n_jobs': -1,
        'verbose': -1
    }

    model = LGBMClassifier(**params)

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        eval_metric='auc',    # eval_metric 'auc'로 변경
        callbacks=[
            early_stopping(stopping_rounds=50, verbose=False),
            log_evaluation(0)
        ]
    )

    preds_proba = model.predict_proba(X_val)[:, 1]
    auc_score = roc_auc_score(y_val, preds_proba)    # PR-AUC 대신 ROC-AUC 계산

    return auc_score

print("ROC-AUC 기준 탐색을 시작합니다...")
study_auc = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))

study_auc.optimize(objective_auc, n_trials=1000)

print("\n" + "="*40)
print(f"최고 ROC-AUC : {study_auc.best_value:.4f}")
print(f"최적 파라미터 : {study_auc.best_params}")
print("="*40)

[I 2026-05-10 10:01:27,805] A new study created in memory with name: no-name-9267bef4-16a3-452b-ab31-476989481fd8

ROC-AUC 기준 탐색을 시작합니다...

[I 2026-05-10 10:01:28,232] Trial 0 finished with value: 0.7283995353808214 and parameters: {'max_depth': 6, 'learning_rate': 0.2536999076681772, 'num_leaves': 51, 'min_child_samples': 104, 'subsample': 0.4936111842654619, 'colsample_bytree': 0.49359671220172163, 'scale_pos_weight': 1.2323344486727978}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:28,966] Trial 1 finished with value: 0.6631928299885524 and parameters: {'max_depth': 10, 'learning_rate': 0.07725378389307355, 'num_leaves': 186, 'min_child_samples': 22, 'subsample': 0.9819459112971965, 'colsample_bytree': 0.899465584480253, 'scale_pos_weight': 1.8493564427131046}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:32,335] Trial 2 finished with value: 0.6563530894769439 and parameters: {'max_depth': 5, 'learning_rate': 0.018659959624904916, 'num_leaves': 20, 'min_child_samples': 93, 'subsample': 0.6591670111852694, 'colsample_bytree': 0.5747374841188252, 'scale_pos_weight': 3.447411578889518}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:32,735] Trial 3 finished with value: 0.6613220434781246 and parameters: {'max_depth': 4, 'learning_rate': 0.027010527749605478, 'num_leaves': 15, 'min_child_samples': 84, 'subsample': 0.8711055768358081, 'colsample_bytree': 0.5198042692950159, 'scale_pos_weight': 3.0569377536544464}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:33,380] Trial 4 finished with value: 0.655376280381673 and parameters: {'max_depth': 8, 'learning_rate': 0.011711509955524094, 'num_leaves': 162, 'min_child_samples': 44, 'subsample': 0.43903095579116774, 'colsample_bytree': 0.9693313223519999, 'scale_pos_weight': 4.862528132298237}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:33,835] Trial 5 finished with value: 0.6939267007355229 and parameters: {'max_depth': 9, 'learning_rate': 0.028180680291847244, 'num_leaves': 38, 'min_child_samples': 116, 'subsample': 0.6640914962437607, 'colsample_bytree': 0.47322294090686734, 'scale_pos_weight': 2.9807076404450807}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:34,192] Trial 6 finished with value: 0.6905082011251359 and parameters: {'max_depth': 4, 'learning_rate': 0.22038218939289875, 'num_leaves': 15, 'min_child_samples': 113, 'subsample': 0.5870266456536466, 'colsample_bytree': 0.7120408127066865, 'scale_pos_weight': 3.1868411173731186}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:34,613] Trial 7 finished with value: 0.6583362406756221 and parameters: {'max_depth': 5, 'learning_rate': 0.27051668818999286, 'num_leaves': 28, 'min_child_samples': 152, 'subsample': 0.9368964102565893, 'colsample_bytree': 0.7587399872866512, 'scale_pos_weight': 4.687496940092467}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:37,320] Trial 8 finished with value: 0.6581957872183694 and parameters: {'max_depth': 4, 'learning_rate': 0.01947558230629543, 'num_leaves': 15, 'min_child_samples': 65, 'subsample': 0.6332063738136893, 'colsample_bytree': 0.5628094190643376, 'scale_pos_weight': 4.314950036607717}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:37,773] Trial 9 finished with value: 0.6747862932199735 and parameters: {'max_depth': 6, 'learning_rate': 0.026000059117302653, 'num_leaves': 42, 'min_child_samples': 39, 'subsample': 0.8813181884524238, 'colsample_bytree': 0.44473038620786254, 'scale_pos_weight': 4.947547746402069}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:38,336] Trial 10 finished with value: 0.6663116968384322 and parameters: {'max_depth': 7, 'learning_rate': 0.11041930924484163, 'num_leaves': 74, 'min_child_samples': 151, 'subsample': 0.4092206423968626, 'colsample_bytree': 0.638826005332106, 'scale_pos_weight': 1.0605769484110275}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:38,927] Trial 11 finished with value: 0.6928075385639725 and parameters: {'max_depth': 9, 'learning_rate': 0.044803827213195854, 'num_leaves': 100, 'min_child_samples': 121, 'subsample': 0.5231595952440065, 'colsample_bytree': 0.4148227746436821, 'scale_pos_weight': 2.093468352595293}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:39,394] Trial 12 finished with value: 0.6487864166699782 and parameters: {'max_depth': 7, 'learning_rate': 0.13919326625843453, 'num_leaves': 52, 'min_child_samples': 125, 'subsample': 0.7399953441345772, 'colsample_bytree': 0.4864547606329562, 'scale_pos_weight': 2.221262795801154}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:40,002] Trial 13 finished with value: 0.701701131907642 and parameters: {'max_depth': 9, 'learning_rate': 0.04802989216041872, 'num_leaves': 113, 'min_child_samples': 96, 'subsample': 0.7329701768884691, 'colsample_bytree': 0.4028305756409444, 'scale_pos_weight': 1.18012984608863}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:40,734] Trial 14 finished with value: 0.6585224039409878 and parameters: {'max_depth': 8, 'learning_rate': 0.05763333406956568, 'num_leaves': 256, 'min_child_samples': 83, 'subsample': 0.7715007264424556, 'colsample_bytree': 0.7980438571671895, 'scale_pos_weight': 1.1927565696529374}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:41,238] Trial 15 finished with value: 0.6488846135165134 and parameters: {'max_depth': 6, 'learning_rate': 0.11968908286187309, 'num_leaves': 53, 'min_child_samples': 106, 'subsample': 0.5262576568832047, 'colsample_bytree': 0.6204273323320096, 'scale_pos_weight': 1.5860133123202542}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:41,872] Trial 16 finished with value: 0.6885504274428773 and parameters: {'max_depth': 10, 'learning_rate': 0.043385674000861546, 'num_leaves': 123, 'min_child_samples': 135, 'subsample': 0.7970621287703783, 'colsample_bytree': 0.40146255860293956, 'scale_pos_weight': 2.495910822966338}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:42,393] Trial 17 finished with value: 0.6665391098323242 and parameters: {'max_depth': 7, 'learning_rate': 0.18491621945096384, 'num_leaves': 76, 'min_child_samples': 68, 'subsample': 0.5268847005225756, 'colsample_bytree': 0.5538457449217988, 'scale_pos_weight': 1.4889931244610481}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:45,876] Trial 18 finished with value: 0.6492838741458586 and parameters: {'max_depth': 8, 'learning_rate': 0.08407654179943178, 'num_leaves': 131, 'min_child_samples': 100, 'subsample': 0.7201587325273631, 'colsample_bytree': 0.6332615168718317, 'scale_pos_weight': 2.6007655078396716}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:46,336] Trial 19 finished with value: 0.6889954771813196 and parameters: {'max_depth': 6, 'learning_rate': 0.06507256941104445, 'num_leaves': 29, 'min_child_samples': 62, 'subsample': 0.8138046551270606, 'colsample_bytree': 0.4772475360232682, 'scale_pos_weight': 3.89624007450854}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:47,166] Trial 20 finished with value: 0.6591598901332447 and parameters: {'max_depth': 9, 'learning_rate': 0.03768025090824123, 'num_leaves': 166, 'min_child_samples': 136, 'subsample': 0.6006252124966275, 'colsample_bytree': 0.8455455006716137, 'scale_pos_weight': 1.4724162794039433}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:47,838] Trial 21 finished with value: 0.6549246156194795 and parameters: {'max_depth': 9, 'learning_rate': 0.029068795084049324, 'num_leaves': 91, 'min_child_samples': 113, 'subsample': 0.6901080876069247, 'colsample_bytree': 0.4806077053544263, 'scale_pos_weight': 3.6933868186177397}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:48,464] Trial 22 finished with value: 0.6991764096576564 and parameters: {'max_depth': 10, 'learning_rate': 0.012868721019456034, 'num_leaves': 108, 'min_child_samples': 94, 'subsample': 0.4611105523021333, 'colsample_bytree': 0.4524101060554352, 'scale_pos_weight': 2.736837915577128}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:49,056] Trial 23 finished with value: 0.7042322132554758 and parameters: {'max_depth': 10, 'learning_rate': 0.011196012607039018, 'num_leaves': 111, 'min_child_samples': 76, 'subsample': 0.47454343158673823, 'colsample_bytree': 0.4082204212843592, 'scale_pos_weight': 1.0464838465102122}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:49,572] Trial 24 finished with value: 0.7045538622520567 and parameters: {'max_depth': 10, 'learning_rate': 0.010011367072041229, 'num_leaves': 72, 'min_child_samples': 80, 'subsample': 0.48204111882047673, 'colsample_bytree': 0.4001445957533858, 'scale_pos_weight': 1.0499578959835028}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:50,207] Trial 25 finished with value: 0.6632706182462356 and parameters: {'max_depth': 10, 'learning_rate': 0.010608169900193873, 'num_leaves': 71, 'min_child_samples': 71, 'subsample': 0.4816532406553635, 'colsample_bytree': 0.499404603616793, 'scale_pos_weight': 1.8966243847806106}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:50,725] Trial 26 finished with value: 0.6684064581644823 and parameters: {'max_depth': 5, 'learning_rate': 0.017263888777578635, 'num_leaves': 23, 'min_child_samples': 48, 'subsample': 0.5699244788906214, 'colsample_bytree': 0.5399199923041511, 'scale_pos_weight': 1.644879915351027}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:51,406] Trial 27 finished with value: 0.7073125079865703 and parameters: {'max_depth': 8, 'learning_rate': 0.013993564074681651, 'num_leaves': 146, 'min_child_samples': 79, 'subsample': 0.40201737543672766, 'colsample_bytree': 0.4321202302951734, 'scale_pos_weight': 1.09554773522124}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:52,103] Trial 28 finished with value: 0.6810881976364693 and parameters: {'max_depth': 8, 'learning_rate': 0.015051638978392508, 'num_leaves': 149, 'min_child_samples': 84, 'subsample': 0.4100083896162182, 'colsample_bytree': 0.5817627309148705, 'scale_pos_weight': 1.399078267183664}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:52,560] Trial 29 finished with value: 0.6820786975660211 and parameters: {'max_depth': 6, 'learning_rate': 0.07990129215368583, 'num_leaves': 51, 'min_child_samples': 21, 'subsample': 0.49804382804891395, 'colsample_bytree': 0.4456549429791089, 'scale_pos_weight': 1.857440409236032}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:53,156] Trial 30 finished with value: 0.6745892609136754 and parameters: {'max_depth': 7, 'learning_rate': 0.021665562818517104, 'num_leaves': 62, 'min_child_samples': 58, 'subsample': 0.40108170271052046, 'colsample_bytree': 0.6964684101987918, 'scale_pos_weight': 2.194633675805412}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:53,852] Trial 31 finished with value: 0.7059483664516351 and parameters: {'max_depth': 10, 'learning_rate': 0.013956226572297621, 'num_leaves': 199, 'min_child_samples': 77, 'subsample': 0.4462056552904754, 'colsample_bytree': 0.42979752525589815, 'scale_pos_weight': 1.0219067617405866}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:54,613] Trial 32 finished with value: 0.6914037909936345 and parameters: {'max_depth': 10, 'learning_rate': 0.014615430995031688, 'num_leaves': 216, 'min_child_samples': 104, 'subsample': 0.4440523962337269, 'colsample_bytree': 0.4355355195780737, 'scale_pos_weight': 1.3330732798819516}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:55,487] Trial 33 finished with value: 0.6866827408800071 and parameters: {'max_depth': 10, 'learning_rate': 0.010272872661611584, 'num_leaves': 216, 'min_child_samples': 78, 'subsample': 0.5562195569421267, 'colsample_bytree': 0.5192286472991674, 'scale_pos_weight': 1.0292334020748257}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:59,313] Trial 34 finished with value: 0.6748206840141462 and parameters: {'max_depth': 9, 'learning_rate': 0.014506120308915916, 'num_leaves': 199, 'min_child_samples': 88, 'subsample': 0.44771534035370947, 'colsample_bytree': 0.5125889420823286, 'scale_pos_weight': 1.714107176085895}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:01:59,999] Trial 35 finished with value: 0.7153786928858212 and parameters: {'max_depth': 9, 'learning_rate': 0.022577918288179042, 'num_leaves': 176, 'min_child_samples': 52, 'subsample': 0.501816001369258, 'colsample_bytree': 0.4497502166517604, 'scale_pos_weight': 1.3226579915690366}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:00,827] Trial 36 finished with value: 0.6738247393511225 and parameters: {'max_depth': 9, 'learning_rate': 0.02256453069020513, 'num_leaves': 181, 'min_child_samples': 35, 'subsample': 0.6198373700281138, 'colsample_bytree': 0.5927559687724029, 'scale_pos_weight': 1.2761360862540232}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:01,904] Trial 37 finished with value: 0.6462227432184731 and parameters: {'max_depth': 8, 'learning_rate': 0.03573204584514762, 'num_leaves': 185, 'min_child_samples': 53, 'subsample': 0.43431611955708505, 'colsample_bytree': 0.998970151699602, 'scale_pos_weight': 1.9069906053628374}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:02,509] Trial 38 finished with value: 0.7112185416360637 and parameters: {'max_depth': 8, 'learning_rate': 0.01822609159273009, 'num_leaves': 155, 'min_child_samples': 33, 'subsample': 0.5547377836271261, 'colsample_bytree': 0.4609453409113345, 'scale_pos_weight': 1.719414298407353}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:03,239] Trial 39 finished with value: 0.6702400014483724 and parameters: {'max_depth': 8, 'learning_rate': 0.017842543823133716, 'num_leaves': 148, 'min_child_samples': 29, 'subsample': 0.5407924774485666, 'colsample_bytree': 0.5294490475680033, 'scale_pos_weight': 1.7120152067605825}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:03,938] Trial 40 finished with value: 0.6535990347887938 and parameters: {'max_depth': 8, 'learning_rate': 0.02345060775135058, 'num_leaves': 157, 'min_child_samples': 31, 'subsample': 0.5099967413027379, 'colsample_bytree': 0.9163645411557048, 'scale_pos_weight': 2.107467617831196}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:04,600] Trial 41 finished with value: 0.7145540840064449 and parameters: {'max_depth': 9, 'learning_rate': 0.01284335646701576, 'num_leaves': 170, 'min_child_samples': 48, 'subsample': 0.9951738792179491, 'colsample_bytree': 0.46133052867031366, 'scale_pos_weight': 1.3289058455605698}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:05,258] Trial 42 finished with value: 0.713729307513625 and parameters: {'max_depth': 9, 'learning_rate': 0.018010548405900922, 'num_leaves': 174, 'min_child_samples': 43, 'subsample': 0.9656063914879106, 'colsample_bytree': 0.46678368432895523, 'scale_pos_weight': 1.3613572549375457}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:05,941] Trial 43 finished with value: 0.713165628909959 and parameters: {'max_depth': 9, 'learning_rate': 0.030828292337348982, 'num_leaves': 171, 'min_child_samples': 44, 'subsample': 0.9938051451894759, 'colsample_bytree': 0.4655989533159894, 'scale_pos_weight': 1.4005488194664248}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:06,867] Trial 44 finished with value: 0.6693029251499254 and parameters: {'max_depth': 9, 'learning_rate': 0.0312038955150108, 'num_leaves': 169, 'min_child_samples': 41, 'subsample': 0.999501385080091, 'colsample_bytree': 0.5023745015853159, 'scale_pos_weight': 1.3307304988452973}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:07,445] Trial 45 finished with value: 0.6308773768114964 and parameters: {'max_depth': 9, 'learning_rate': 0.28080519467276316, 'num_leaves': 174, 'min_child_samples': 53, 'subsample': 0.9352920825127734, 'colsample_bytree': 0.4800834275235386, 'scale_pos_weight': 2.3448824196691826}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:07,959] Trial 46 finished with value: 0.6723425144456114 and parameters: {'max_depth': 5, 'learning_rate': 0.024859028830084905, 'num_leaves': 17, 'min_child_samples': 43, 'subsample': 0.9519102857552391, 'colsample_bytree': 0.5581866214197835, 'scale_pos_weight': 1.495393271865661}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:08,746] Trial 47 finished with value: 0.6765028981914357 and parameters: {'max_depth': 9, 'learning_rate': 0.03211894012752601, 'num_leaves': 196, 'min_child_samples': 49, 'subsample': 0.901507534551519, 'colsample_bytree': 0.6032446440978709, 'scale_pos_weight': 2.0046162518536708}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:12,788] Trial 48 finished with value: 0.6696765763675493 and parameters: {'max_depth': 9, 'learning_rate': 0.02069244156146959, 'num_leaves': 214, 'min_child_samples': 59, 'subsample': 0.9645455957760357, 'colsample_bytree': 0.6583241165022001, 'scale_pos_weight': 1.253980398410509}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:13,315] Trial 49 finished with value: 0.6629194374430487 and parameters: {'max_depth': 7, 'learning_rate': 0.1832352811540606, 'num_leaves': 123, 'min_child_samples': 26, 'subsample': 0.9151101006407759, 'colsample_bytree': 0.4554316916850748, 'scale_pos_weight': 3.0791831002152446}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:13,717] Trial 50 finished with value: 0.6638148110361363 and parameters: {'max_depth': 4, 'learning_rate': 0.027417688095404215, 'num_leaves': 15, 'min_child_samples': 36, 'subsample': 0.8577296727685144, 'colsample_bytree': 0.5374390025945517, 'scale_pos_weight': 3.2991486094008717}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:14,360] Trial 51 finished with value: 0.7107154429765463 and parameters: {'max_depth': 8, 'learning_rate': 0.01721142348545275, 'num_leaves': 160, 'min_child_samples': 49, 'subsample': 0.9915460433340668, 'colsample_bytree': 0.4699538750769223, 'scale_pos_weight': 1.7025965518494908}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:15,029] Trial 52 finished with value: 0.7128624330120557 and parameters: {'max_depth': 9, 'learning_rate': 0.01842592166354362, 'num_leaves': 191, 'min_child_samples': 34, 'subsample': 0.8458491202698559, 'colsample_bytree': 0.45582238932640584, 'scale_pos_weight': 1.538365100419266}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:15,856] Trial 53 finished with value: 0.6836691851361543 and parameters: {'max_depth': 9, 'learning_rate': 0.012441962739668064, 'num_leaves': 236, 'min_child_samples': 25, 'subsample': 0.8659735059214714, 'colsample_bytree': 0.4973587584635118, 'scale_pos_weight': 1.5161908082378277}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:16,496] Trial 54 finished with value: 0.7011697864779192 and parameters: {'max_depth': 9, 'learning_rate': 0.01925807288104946, 'num_leaves': 138, 'min_child_samples': 39, 'subsample': 0.9705772649822557, 'colsample_bytree': 0.42425722704155944, 'scale_pos_weight': 1.2215142251941002}. Best is trial 0 with value: 0.7283995353808214.
[I 2026-05-10 10:02:16,931] Trial 55 finished with value: 0.6920443140531207 and parameters: {'max_depth': 6, 'learning_rate': 0.10114812728041478, 'num_leaves': 39, 'min_child_samples': 45, 'subsample': 0.9294688861297474, 'colsample_bytree': 0.4630136135748497, 'scale_pos_weight': 1.3757440509338303}. Best is trial 0 with value: 0.7283995353808214.

========================================
최고 ROC-AUC : 0.7496
최적 파라미터 : {'max_depth': 5, 'learning_rate': 0.16846100748961326, 'num_leaves': 20, 'min_child_samples': 62, 'subsample': 0.657706798505073, 'colsample_bytree': 0.4886885979244237, 'scale_pos_weight': 1.1370046342002038}
========================================

- 최고 ROC-AUC : 0.7496
- 최적 파라미터 : {'max_depth': 5, 'learning_rate': 0.16846100748961326, 'num_leaves': 20, 'min_child_samples': 62, 'subsample': 0.657706798505073, 'colsample_bytree': 0.4886885979244237, 'scale_pos_weight': 1.1370046342002038}

#### f1_Score 기준 하이퍼파라미터 튜닝

In [ ]:
def objective_f1(trial):
    max_depth = trial.suggest_int('max_depth', 4, 10)
    max_leaves_limit = min(2 ** max_depth, 256)

    params = {
        'n_estimators': 2000,
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'max_depth': max_depth,
        'num_leaves': trial.suggest_int('num_leaves', 15, max_leaves_limit),
        'min_child_samples': trial.suggest_int('min_child_samples', 20, 160),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1.0, 5.0),
        'random_state': 42,
        'n_jobs': -1,
        'verbose': -1
    }

    model = LGBMClassifier(**params)

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        eval_metric='binary_logloss',   # 기본값
        callbacks=[
            early_stopping(stopping_rounds=50, verbose=False),
            log_evaluation(0)
        ]
    )

    preds_proba = model.predict_proba(X_val)[:, 1]
    preds_class = (preds_proba > 0.5).astype(int)    # 기본 threshold = 0.5 이용해 f1_score 계산

    f1 = f1_score(y_val, preds_class)

    return f1

study_f1 = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study_f1.optimize(objective_f1, n_trials=1000)

print("\n" + "="*40)
print(f"최고 F1-score : {study_f1.best_value:.4f}")
print(f"최적 파라미터 : {study_f1.best_params}")
print("="*40)

[I 2026-05-10 10:18:41,925] A new study created in memory with name: no-name-4b913ab9-21fe-4721-a1fe-fc3ae210527e
[I 2026-05-10 10:18:43,204] Trial 0 finished with value: 0.12631318749227538 and parameters: {'max_depth': 6, 'learning_rate': 0.2536999076681772, 'num_leaves': 51, 'min_child_samples': 104, 'subsample': 0.4936111842654619, 'colsample_bytree': 0.49359671220172163, 'scale_pos_weight': 1.2323344486727978}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:43,863] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.07725378389307355, 'num_leaves': 186, 'min_child_samples': 22, 'subsample': 0.9819459112971965, 'colsample_bytree': 0.899465584480253, 'scale_pos_weight': 1.8493564427131046}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:44,165] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.018659959624904916, 'num_leaves': 20, 'min_child_samples': 93, 'subsample': 0.6591670111852694, 'colsample_bytree': 0.5747374841188252, 'scale_pos_weight': 3.447411578889518}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:44,436] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.027010527749605478, 'num_leaves': 15, 'min_child_samples': 84, 'subsample': 0.8711055768358081, 'colsample_bytree': 0.5198042692950159, 'scale_pos_weight': 3.0569377536544464}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:45,088] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.011711509955524094, 'num_leaves': 162, 'min_child_samples': 44, 'subsample': 0.43903095579116774, 'colsample_bytree': 0.9693313223519999, 'scale_pos_weight': 4.862528132298237}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:45,449] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.028180680291847244, 'num_leaves': 38, 'min_child_samples': 116, 'subsample': 0.6640914962437607, 'colsample_bytree': 0.47322294090686734, 'scale_pos_weight': 2.9807076404450807}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:45,728] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.22038218939289875, 'num_leaves': 15, 'min_child_samples': 113, 'subsample': 0.5870266456536466, 'colsample_bytree': 0.7120408127066865, 'scale_pos_weight': 3.1868411173731186}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:45,997] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.27051668818999286, 'num_leaves': 28, 'min_child_samples': 152, 'subsample': 0.9368964102565893, 'colsample_bytree': 0.7587399872866512, 'scale_pos_weight': 4.687496940092467}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:46,274] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.01947558230629543, 'num_leaves': 15, 'min_child_samples': 65, 'subsample': 0.6332063738136893, 'colsample_bytree': 0.5628094190643376, 'scale_pos_weight': 4.314950036607717}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:46,595] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.026000059117302653, 'num_leaves': 42, 'min_child_samples': 39, 'subsample': 0.8813181884524238, 'colsample_bytree': 0.44473038620786254, 'scale_pos_weight': 4.947547746402069}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:47,025] Trial 10 finished with value: 0.02072829131652661 and parameters: {'max_depth': 7, 'learning_rate': 0.11041930924484163, 'num_leaves': 74, 'min_child_samples': 151, 'subsample': 0.4092206423968626, 'colsample_bytree': 0.638826005332106, 'scale_pos_weight': 1.0605769484110275}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:47,437] Trial 11 finished with value: 0.037509480797076465 and parameters: {'max_depth': 7, 'learning_rate': 0.11824860277369731, 'num_leaves': 75, 'min_child_samples': 160, 'subsample': 0.40553660142667064, 'colsample_bytree': 0.6489946910281852, 'scale_pos_weight': 1.1142544689718272}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:47,872] Trial 12 finished with value: 0.04639033763381828 and parameters: {'max_depth': 7, 'learning_rate': 0.14491980862121354, 'num_leaves': 75, 'min_child_samples': 129, 'subsample': 0.5212969114999868, 'colsample_bytree': 0.7875138644219446, 'scale_pos_weight': 1.2538121673565934}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:48,206] Trial 13 finished with value: 0.0002858367871945119 and parameters: {'max_depth': 6, 'learning_rate': 0.16102006905099078, 'num_leaves': 52, 'min_child_samples': 127, 'subsample': 0.5321334622806678, 'colsample_bytree': 0.7970010847283225, 'scale_pos_weight': 1.9085560466035143}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:48,653] Trial 14 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.05470901570558554, 'num_leaves': 94, 'min_child_samples': 129, 'subsample': 0.7715007264424556, 'colsample_bytree': 0.8554762280300234, 'scale_pos_weight': 1.7954065826788188}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:49,079] Trial 15 finished with value: 0.002276931834353209 and parameters: {'max_depth': 8, 'learning_rate': 0.2910727136091532, 'num_leaves': 248, 'min_child_samples': 90, 'subsample': 0.5175573931311073, 'colsample_bytree': 0.8231901906062562, 'scale_pos_weight': 2.280794868779526}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:49,414] Trial 16 finished with value: 0.05926527298558961 and parameters: {'max_depth': 6, 'learning_rate': 0.16346250553431854, 'num_leaves': 52, 'min_child_samples': 106, 'subsample': 0.7537591011074556, 'colsample_bytree': 0.40210349403270573, 'scale_pos_weight': 1.3847883800021843}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:49,760] Trial 17 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.06735875260805087, 'num_leaves': 49, 'min_child_samples': 68, 'subsample': 0.7597011029541516, 'colsample_bytree': 0.4028440717918536, 'scale_pos_weight': 2.2590994364880035}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:50,069] Trial 18 finished with value: 0.05387843508866928 and parameters: {'max_depth': 5, 'learning_rate': 0.17178329359598116, 'num_leaves': 23, 'min_child_samples': 102, 'subsample': 0.7942871825965369, 'colsample_bytree': 0.4930435302735239, 'scale_pos_weight': 1.4271843086035723}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:50,421] Trial 19 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.044207413119892784, 'num_leaves': 53, 'min_child_samples': 70, 'subsample': 0.7235636673487791, 'colsample_bytree': 0.4127398496996548, 'scale_pos_weight': 2.666474929475738}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:50,936] Trial 20 finished with value: 0.034907881978113314 and parameters: {'max_depth': 8, 'learning_rate': 0.09437181416235813, 'num_leaves': 118, 'min_child_samples': 107, 'subsample': 0.8439850484527895, 'colsample_bytree': 0.565661722759616, 'scale_pos_weight': 1.5558881719873738}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:51,223] Trial 21 finished with value: 0.08501997772974389 and parameters: {'max_depth': 5, 'learning_rate': 0.20636273900852928, 'num_leaves': 22, 'min_child_samples': 99, 'subsample': 0.8088921976847346, 'colsample_bytree': 0.49639450730552004, 'scale_pos_weight': 1.5098094050360034}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:51,496] Trial 22 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.21223187734683788, 'num_leaves': 21, 'min_child_samples': 78, 'subsample': 0.7143323283697285, 'colsample_bytree': 0.5211265897556386, 'scale_pos_weight': 2.1744223157167304}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:51,813] Trial 23 finished with value: 0.0038434163701067618 and parameters: {'max_depth': 6, 'learning_rate': 0.19358192904501223, 'num_leaves': 43, 'min_child_samples': 98, 'subsample': 0.8331466327017071, 'colsample_bytree': 0.45150667359311303, 'scale_pos_weight': 1.5899689331686602}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:52,097] Trial 24 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.13542174377323946, 'num_leaves': 20, 'min_child_samples': 119, 'subsample': 0.6048516357153626, 'colsample_bytree': 0.6170875147893499, 'scale_pos_weight': 3.874958133168993}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:52,404] Trial 25 finished with value: 0.012354345079320511 and parameters: {'max_depth': 6, 'learning_rate': 0.24849213164362383, 'num_leaves': 33, 'min_child_samples': 141, 'subsample': 0.9143205693352344, 'colsample_bytree': 0.5153549392872497, 'scale_pos_weight': 1.4071931245917817}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:52,671] Trial 26 finished with value: 0.010687666994796794 and parameters: {'max_depth': 5, 'learning_rate': 0.29035445179922365, 'num_leaves': 18, 'min_child_samples': 107, 'subsample': 0.8025414586920953, 'colsample_bytree': 0.4477841170360377, 'scale_pos_weight': 2.5326862829009045}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:53,151] Trial 27 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.08801777007525995, 'num_leaves': 16, 'min_child_samples': 80, 'subsample': 0.7186228586121884, 'colsample_bytree': 0.6994056283878103, 'scale_pos_weight': 1.9893883778327504}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:55,949] Trial 28 finished with value: 0.027374418119919405 and parameters: {'max_depth': 6, 'learning_rate': 0.18539253460543514, 'num_leaves': 46, 'min_child_samples': 140, 'subsample': 0.4747840897016179, 'colsample_bytree': 0.40572954658660515, 'scale_pos_weight': 1.0822902027252082}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:56,730] Trial 29 finished with value: 0.012566184256971409 and parameters: {'max_depth': 9, 'learning_rate': 0.07269105002458973, 'num_leaves': 110, 'min_child_samples': 58, 'subsample': 0.9526208545046689, 'colsample_bytree': 0.6107671721321886, 'scale_pos_weight': 1.7164569595552743}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:57,260] Trial 30 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.11600812692117021, 'num_leaves': 140, 'min_child_samples': 88, 'subsample': 0.7503748406605557, 'colsample_bytree': 0.4861839936042649, 'scale_pos_weight': 2.550068790977359}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:57,562] Trial 31 finished with value: 0.04515908313376668 and parameters: {'max_depth': 5, 'learning_rate': 0.16907624179499384, 'num_leaves': 23, 'min_child_samples': 101, 'subsample': 0.8163277734731338, 'colsample_bytree': 0.5196012697538385, 'scale_pos_weight': 1.3810705682460196}. Best is trial 0 with value: 0.12631318749227538.
[I 2026-05-10 10:18:57,859] Trial 32 finished with value: 0.1420649261636239 and parameters: {'max_depth': 5, 'learning_rate': 0.22567244027795605, 'num_leaves': 24, 'min_child_samples': 104, 'subsample': 0.6702753917278108, 'colsample_bytree': 0.4856768435682889, 'scale_pos_weight': 1.4606011101754215}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:18:58,179] Trial 33 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.20370418706558824, 'num_leaves': 26, 'min_child_samples': 98, 'subsample': 0.6893636806548479, 'colsample_bytree': 0.5526572528281142, 'scale_pos_weight': 2.0588687992187165}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:18:58,433] Trial 34 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.24246864485752925, 'num_leaves': 16, 'min_child_samples': 118, 'subsample': 0.5642106013639528, 'colsample_bytree': 0.4317470125616834, 'scale_pos_weight': 1.714107176085895}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:18:58,768] Trial 35 finished with value: 0.048351947698174885 and parameters: {'max_depth': 6, 'learning_rate': 0.13168804170612686, 'num_leaves': 34, 'min_child_samples': 93, 'subsample': 0.994287729341779, 'colsample_bytree': 0.47368594625231303, 'scale_pos_weight': 1.2726585839966795}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:18:59,052] Trial 36 finished with value: 0.0001429286071607232 and parameters: {'max_depth': 5, 'learning_rate': 0.23193341526074604, 'num_leaves': 21, 'min_child_samples': 109, 'subsample': 0.6666385090054386, 'colsample_bytree': 0.9187264205229493, 'scale_pos_weight': 1.5802996614854823}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:18:59,382] Trial 37 finished with value: 0.03592319867868694 and parameters: {'max_depth': 4, 'learning_rate': 0.15282347601230947, 'num_leaves': 15, 'min_child_samples': 121, 'subsample': 0.8692979387042705, 'colsample_bytree': 0.5394427576727896, 'scale_pos_weight': 1.00913928590156}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:18:59,819] Trial 38 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.011720241605177305, 'num_leaves': 60, 'min_child_samples': 82, 'subsample': 0.6310994966313175, 'colsample_bytree': 0.595743680454742, 'scale_pos_weight': 3.402327579699989}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:00,126] Trial 39 finished with value: 0.041389406441309555 and parameters: {'max_depth': 6, 'learning_rate': 0.2982399223380971, 'num_leaves': 29, 'min_child_samples': 112, 'subsample': 0.6909383975532526, 'colsample_bytree': 0.6913739486882617, 'scale_pos_weight': 2.7988222228957254}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:00,402] Trial 40 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.04195801009241162, 'num_leaves': 15, 'min_child_samples': 53, 'subsample': 0.49136609754302357, 'colsample_bytree': 0.4854098035318955, 'scale_pos_weight': 3.9514821874120045}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:00,697] Trial 41 finished with value: 0.04869399167973812 and parameters: {'max_depth': 5, 'learning_rate': 0.17767265542094512, 'num_leaves': 23, 'min_child_samples': 105, 'subsample': 0.7821306752558344, 'colsample_bytree': 0.49675735283237693, 'scale_pos_weight': 1.508887116809612}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:00,989] Trial 42 finished with value: 0.08646938641007051 and parameters: {'max_depth': 5, 'learning_rate': 0.2269798094384727, 'num_leaves': 24, 'min_child_samples': 23, 'subsample': 0.7973865774703018, 'colsample_bytree': 0.454682768377863, 'scale_pos_weight': 1.2584686304437576}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:01,313] Trial 43 finished with value: 0.12741139524450426 and parameters: {'max_depth': 5, 'learning_rate': 0.24426977245306591, 'num_leaves': 25, 'min_child_samples': 36, 'subsample': 0.8295309530742497, 'colsample_bytree': 0.4596512469740559, 'scale_pos_weight': 1.2386023572060263}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:01,608] Trial 44 finished with value: 0.06778298727394508 and parameters: {'max_depth': 5, 'learning_rate': 0.22937219023827765, 'num_leaves': 25, 'min_child_samples': 20, 'subsample': 0.895147890250738, 'colsample_bytree': 0.4579525538079671, 'scale_pos_weight': 1.2094010477420551}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:01,870] Trial 45 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.2566139761983518, 'num_leaves': 16, 'min_child_samples': 33, 'subsample': 0.8568611576191508, 'colsample_bytree': 0.5895351003426074, 'scale_pos_weight': 1.829015830836}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:02,167] Trial 46 finished with value: 0.04124278251306021 and parameters: {'max_depth': 5, 'learning_rate': 0.1992896128901089, 'num_leaves': 25, 'min_child_samples': 31, 'subsample': 0.8224372600506951, 'colsample_bytree': 0.4629871114100981, 'scale_pos_weight': 1.1533070233518854}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:02,505] Trial 47 finished with value: 0.13493763386670027 and parameters: {'max_depth': 5, 'learning_rate': 0.25797420424879597, 'num_leaves': 24, 'min_child_samples': 43, 'subsample': 0.9068207961384885, 'colsample_bytree': 0.5362455448542065, 'scale_pos_weight': 1.2404334862333286}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:02,819] Trial 48 finished with value: 0.0955792975497409 and parameters: {'max_depth': 4, 'learning_rate': 0.26625863413641576, 'num_leaves': 16, 'min_child_samples': 28, 'subsample': 0.9615917451957164, 'colsample_bytree': 0.6583241165022001, 'scale_pos_weight': 1.0100343427815448}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:03,083] Trial 49 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.26424093465060494, 'num_leaves': 15, 'min_child_samples': 46, 'subsample': 0.9628925833344189, 'colsample_bytree': 0.6562228322482011, 'scale_pos_weight': 1.689060457880731}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:03,454] Trial 50 finished with value: 0.07333244927728418 and parameters: {'max_depth': 4, 'learning_rate': 0.09808306762039783, 'num_leaves': 15, 'min_child_samples': 41, 'subsample': 0.9121036429375116, 'colsample_bytree': 0.7344820729983877, 'scale_pos_weight': 1.05610607840554}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:03,746] Trial 51 finished with value: 0.012432890647075446 and parameters: {'max_depth': 5, 'learning_rate': 0.29665191720929246, 'num_leaves': 25, 'min_child_samples': 25, 'subsample': 0.9716396434230062, 'colsample_bytree': 0.5345224165919158, 'scale_pos_weight': 1.2800685046630318}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:04,028] Trial 52 finished with value: 0.1282435129740519 and parameters: {'max_depth': 4, 'learning_rate': 0.22664402224294636, 'num_leaves': 16, 'min_child_samples': 28, 'subsample': 0.9261735467710339, 'colsample_bytree': 0.5679443096268616, 'scale_pos_weight': 1.3011411616109967}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:04,304] Trial 53 finished with value: 0.04503020318506315 and parameters: {'max_depth': 4, 'learning_rate': 0.2647312595715831, 'num_leaves': 15, 'min_child_samples': 32, 'subsample': 0.9343342862267601, 'colsample_bytree': 0.577422651409938, 'scale_pos_weight': 1.016150386515515}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:04,592] Trial 54 finished with value: 0.032939884710403516 and parameters: {'max_depth': 4, 'learning_rate': 0.15227586394309778, 'num_leaves': 16, 'min_child_samples': 47, 'subsample': 0.9409270066827071, 'colsample_bytree': 0.65216981021013, 'scale_pos_weight': 1.3662967454130774}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:04,872] Trial 55 finished with value: 0.025201893622946253 and parameters: {'max_depth': 4, 'learning_rate': 0.21699042444568808, 'num_leaves': 15, 'min_child_samples': 34, 'subsample': 0.9167819071225675, 'colsample_bytree': 0.5470762543173854, 'scale_pos_weight': 1.2029581986472453}. Best is trial 32 with value: 0.1420649261636239.
[I 2026-05-10 10:19:05,184] Trial 56 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.18255006703023685, 'num_leaves': 29, 'min_child_samples': 52, 'subsample': 0.8874361804025375, 'colsample_bytree': 0.6314581226657087, 'scale_pos_weight': 1.9722860945702303}. Best is trial 32 with value: 0.1420649261636239.

========================================
최고 F1-score : 0.2697
최적 파라미터 : {'max_depth': 5, 'learning_rate': 0.29892386276823396, 'num_leaves': 24, 'min_child_samples': 97, 'subsample': 0.433787601904423, 'colsample_bytree': 0.7983142308040867, 'scale_pos_weight': 1.4238253021337417}
========================================

- 최고 F1-score : 0.2697
- 최적 파라미터 : {'max_depth': 5, 'learning_rate': 0.29892386276823396, 'num_leaves': 24, 'min_child_samples': 97, 'subsample': 0.433787601904423, 'colsample_bytree': 0.7983142308040867, 'scale_pos_weight': 1.4238253021337417}

-> f1-score 기준, 성능이 0.3에 미치지 못하는 poor한 모습이므로 threshold 조정해야 함!

#### threshold 조정 전 튜닝 결과 비교

In [ ]:
def evaluate_baseline_model(params, model_name="Model"):
    print(f"\n[{model_name} 기본(Threshold 0.5) 성능 평가]")

    # 1. 모델 학습
    model = LGBMClassifier(**params, n_estimators=2000, random_state=42, n_jobs=-1, verbose=-1)
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[early_stopping(stopping_rounds=50, verbose=False)]
    )

    # 2. 확률값 예측
    preds_proba = model.predict_proba(X_val)[:, 1]

    # 기본 threshold
    default_threshold = 0.5
    final_preds = (preds_proba >= default_threshold).astype(int)

    # 성능 지표 계산
    roc_auc = roc_auc_score(y_val, preds_proba)
    pr_auc = average_precision_score(y_val, preds_proba)

    f1 = f1_score(y_val, final_preds)
    precision = precision_score(y_val, final_preds)
    recall = recall_score(y_val, final_preds)
    cm = confusion_matrix(y_val, final_preds)

    print("=" * 50)
    print(f"📊 {model_name} 성능 리포트 (Threshold: 0.5 고정)")
    print("=" * 50)
    print(f"• PR-AUC   : {pr_auc:.4f} (임계값 무관)")
    print(f"• ROC-AUC  : {roc_auc:.4f} (임계값 무관)")
    print("-" * 50)
    print(f"• F1-Score : {f1:.4f}")
    print(f"• Precision: {precision:.4f}")
    print(f"• Recall   : {recall:.4f}")
    print("-" * 50)
    print("📌 Confusion Matrix:")
    print(f"TN: {cm[0][0]} | FP: {cm[0][1]}")
    print(f"FN: {cm[1][0]} | TP: {cm[1][1]}")
    print("=" * 50)

params_prauc = {'max_depth': 5, 'learning_rate': 0.3471822878189745, 'num_leaves': 23, 'min_child_samples': 144, 'subsample': 0.5111636910456923, 'colsample_bytree': 0.5646394676662235, 'scale_pos_weight': 1.0061636591457408}
params_auc = {'max_depth': 5, 'learning_rate': 0.16846100748961326, 'num_leaves': 20, 'min_child_samples': 62, 'subsample': 0.657706798505073, 'colsample_bytree': 0.4886885979244237, 'scale_pos_weight': 1.1370046342002038}

evaluate_baseline_model(params_prauc, "PR-AUC 타겟 모델")
evaluate_baseline_model(params_auc, "ROC-AUC 타겟 모델")

[PR-AUC 타겟 모델 기본(Threshold 0.5) 성능 평가]
==================================================
📊 PR-AUC 타겟 모델 성능 리포트 (Threshold: 0.5 고정)
==================================================
• PR-AUC   : 0.4106 (임계값 무관)
• ROC-AUC  : 0.7404 (임계값 무관)
--------------------------------------------------
• F1-Score : 0.0099
• Precision: 0.6034
• Recall   : 0.0050
--------------------------------------------------
📌 Confusion Matrix:
TN: 59436 | FP: 46
FN: 13922 | TP: 70
==================================================

[ROC-AUC 타겟 모델 기본(Threshold 0.5) 성능 평가]
==================================================
📊 ROC-AUC 타겟 모델 성능 리포트 (Threshold: 0.5 고정)
==================================================
• PR-AUC   : 0.3508 (임계값 무관)
• ROC-AUC  : 0.7081 (임계값 무관)
--------------------------------------------------
• F1-Score : 0.0507
• Precision: 0.5096
• Recall   : 0.0267
--------------------------------------------------
📌 Confusion Matrix:
TN: 59123 | FP: 359
FN: 13619 | TP: 373
==================================================

### threshold 튜닝 후 성능지표

In [16]:
# PR-AUC 기준 타겟 파라미터
best_params = {
    'max_depth': 5,
    'learning_rate': 0.3471822878189745,
    'num_leaves': 23,
    'min_child_samples': 144,
    'subsample': 0.5111636910456923,
    'colsample_bytree': 0.5646394676662235,
    'scale_pos_weight': 1.0061636591457408,
    'n_estimators': 2000,
    'random_state': 42,
    'n_jobs': -1,
    'verbose': -1
}

# 모델 학습
model = LGBMClassifier(**best_params)
model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    callbacks=[early_stopping(stopping_rounds=50, verbose=False)]
)

# ---- Validation: F1 최대 Threshold 탐색 ----
preds_proba = model.predict_proba(X_val)[:, 1]
precisions, recalls, thresholds = precision_recall_curve(y_val, preds_proba)

f1_scores = np.divide(
    2 * (precisions * recalls), (precisions + recalls),
    out=np.zeros_like(precisions), where=(precisions + recalls) != 0
)
best_threshold = thresholds[np.argmax(f1_scores)]

final_preds = (preds_proba >= best_threshold).astype(int)
print(f"최적 Threshold : {best_threshold:.4f}")

# ---- Test 평가 ----
test_preds_proba = model.predict_proba(X_test)[:, 1]
test_final_preds = (test_preds_proba >= best_threshold).astype(int)

print("\n[최종 테스트 결과]")
print(f"PR-AUC   : {average_precision_score(y_test, test_preds_proba):.4f}")
print(f"ROC-AUC  : {roc_auc_score(y_test, test_preds_proba):.4f}")
print(f"F1-Score : {f1_score(y_test, test_final_preds):.4f}")
print(f"Precision: {precision_score(y_test, test_final_preds):.4f}")
print(f"Recall   : {recall_score(y_test, test_final_preds):.4f}")

test_cm = confusion_matrix(y_test, test_final_preds)
print(f"TN: {test_cm[0][0]:,} | FP: {test_cm[0][1]:,}")
print(f"FN: {test_cm[1][0]:,} | TP: {test_cm[1][1]:,}")

최적 Threshold : 0.2233

[최종 테스트 결과]
PR-AUC   : 0.3248
ROC-AUC  : 0.7197
F1-Score : 0.3870
Precision: 0.2974
Recall   : 0.5541
TN: 47,505 | FP: 15,967
FN: 5,438 | TP: 6,757

In [17]:
# mean(y_pred)
final_preds.mean()

np.float64(0.3170509295805319)